### ISSUE TITLE
 Failed execv  because non-0 exit status

### ISSUE THREAD

**Issue by qinlicang** [rovo89/XposedBridge#112]
device: zuk z1
android version: 6.0.1
xposed-v86-sdk23-arm.zip
XposedInstaller_3.0_alpha4.apk

 W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg /system/framework/XposedBridge.jar --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xnorelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/system/priv-app/Xlog/oat/arm/Xlog.odex --oat-file=/data/dalvik-cache/arm/system@priv-app@Xlog@Xlog.apk@classes.dex) because non-0 exit status

D/StrictMode: StrictMode policy violation; ~duration=7 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2
                                                 at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1263)
                                                 at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:292)
                                                 at java.io.File.lastModified(File.java:610)
                                                 at android.content.res.XResources.isFirstLoad(XResources.java:114)
                                                 at de.robv.android.xposed.XposedInit$7.afterHookedMethod(XposedInit.java:269)
                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
                                                 at android.app.ResourcesManager.getTopLevelResources(<Xposed>)
                                                 at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1710)
                                                 at android.app.LoadedApk.getResources(LoadedApk.java:551)
                                                 at android.app.ContextImpl.<init>(ContextImpl.java:1910)
                                                 at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:1756)
                                                 at android.app.ContextImpl.createPackageContext(ContextImpl.java:1720)
                                                 at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:754)
                                                 at android.app.ActivityThread.installProvider(ActivityThread.java:5182)
                                                 at android.app.ActivityThread.installContentProviders(ActivityThread.java:4804)
                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4744)
                                                 at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
                                                 at android.app.ActivityThread.handleBindApplication(<Xposed>)
                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:153)
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1408)
                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                 at android.os.Looper.loop(Looper.java:148)
                                                 at android.app.ActivityThread.main(ActivityThread.java:5473)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by qinlicang** [comment]
"Failed execv" don't affect xposed framework, i modify apk,  then apk run succeed!

**Comment by rovo89** [comment]
The Java stack isn't related to the execv failure - and the latter doesn't necessarily mean that something went wrong. Without more context (i.e. more log lines), I can't say more, but glad you fixed your issue.

**Comment by lorak06** [comment]
But what did you modify ?
