### ISSUE TITLE
Print services doesn't work

### ISSUE THREAD

**Issue by ajmtrz** [rovo89/XposedBridge#117]
```
08-12 13:12:41.153  5305  5352 E RemotePrintSpooler: Error getting print jobs.
08-12 13:12:41.153  5305  5352 E RemotePrintSpooler: java.util.concurrent.TimeoutException: Cannot get spooler!
08-12 13:12:41.153  5305  5352 E RemotePrintSpooler:    at com.android.server.print.RemotePrintSpooler.bindLocked(RemotePrintSpooler.java:378)
08-12 13:12:41.153  5305  5352 E RemotePrintSpooler:    at com.android.server.print.RemotePrintSpooler.getRemoteInstanceLazy(RemotePrintSpooler.java:354)
08-12 13:12:41.153  5305  5352 E RemotePrintSpooler:    at com.android.server.print.RemotePrintSpooler.getPrintJobInfos(RemotePrintSpooler.java:115)
08-12 13:12:41.153  5305  5352 E RemotePrintSpooler:    at com.android.server.print.UserState.getPrintJobInfos(UserState.java:243)
08-12 13:12:41.153  5305  5352 E RemotePrintSpooler:    at com.android.server.print.PrintManagerService$PrintManagerImpl.getPrintJobInfos(PrintManagerService.java:157)
08-12 13:12:41.153  5305  5352 E RemotePrintSpooler:    at android.print.IPrintManager$Stub.onTransact(IPrintManager.java:57)
08-12 13:12:41.153  5305  5352 E RemotePrintSpooler:    at android.os.Binder.execTransact(Binder.java:453)
08-12 13:12:41.160  5305  5876 W ActivityManager: Unable to start service Intent { cmp=com.android.printspooler/.model.PrintSpoolerService } U=0: not found
08-12 13:12:46.688  5305  7802 W ActivityManager: Unable to start service Intent { cmp=com.android.printspooler/.model.PrintSpoolerService } U=0: not found
08-12 13:12:46.689  5305  6731 I ActivityManager: START u0 {act=android.print.PRINT_DIALOG dat=printjob:8dd145e6-6c80-4542-8c03-3ccc3d63acf0 (has extras)} from uid 1000 on display 0
```

**Comment by rovo89** [comment]
... and why do you think this is related to Xposed?

**Comment by ajmtrz** [comment]
because without xposed works.

**Comment by rovo89** [comment]
Well, then follow: https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by ajmtrz** [comment]
Ok. My platform is Motorola Nexus 6 with latest android MOB30W.
My Xposed version is v86.
Issue: When I try print document from Google Document or other aplication like Firefox, android cannot get printers and crash as above.
Thanks @rovo89

**Comment by rovo89** [comment]
Hm, but I still need a detailed log. There isn't any indication that Xposed is involved in the log you posted.

**Comment by ajmtrz** [comment]
true

**Comment by ajmtrz** [comment]
I cannot send you any xposed involved log because only appears that log (logcat -b all). But if I unninstall Xposed works. Sorry I cannot send more .

**Comment by rovo89** [comment]
Then I'm afraid I can't help you at this time. In case you're able to find more details later, please let me know.

**Comment by ajmtrz** [comment]
The issue is caused by Supersu. Sorry. In my build, when I install supersu via recovery zip, xposed is enabled by supersu. So, I thought that issue was caused by xposed. I 'm sorry for wasting time. Thanks always @rovo89
