### ISSUE TITLE
de.robv.android.xposed.XposedHelpers$ClassNotFoundError

### ISSUE THREAD

**Issue by pashaie** [rovo89/XposedBridge#120]
I'm trying to hook an app that is obfuscated (I'm not quit sure with what).
The problem is, lpparam.classLoader in handleLoadPackage is empty as far as I can find.
Looking in it's deobfuscated  code, there is no custom classloader that can be found.

here is the problematic code:

``` java
Class<?>someappTargetClass = XposedHelpers.findClass(
                    "com/somecompany/someapp/h/ac", lpparam.classLoader);
```

the error:

``` java
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com/somecompany/someapp/h/ac
      at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
      at someapp.ir.someappspy.Main.handleLoadPackage(Main.java:63)
      at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
      at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
      at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
      at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
      at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
      at android.app.ActivityThread.handleBindApplication(Native Method)
      at android.app.ActivityThread.access$1300(ActivityThread.java:141)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loop(Looper.java:137)
      at android.app.ActivityThread.main(ActivityThread.java:5041)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:511)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
      at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.ClassNotFoundException: com/somecompany/someapp/h/ac
      at java.lang.Class.classForName(Native Method)
      at java.lang.Class.forName(Class.java:217)
      at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
      at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
      ... 18 more
```

also, worth mentioning that I tried to get all classed that were loaded by classloader with reflection, but surprisingly there was none.

``` java
Field[] allFields = lpparam.classLoader.getClass().getDeclaredFields();
XposedBridge.log("length " + allFields.length );
for (Field field : allFields) {
    XposedBridge.log("---------> :::: " + field );
}
//output: length 0
```

another approach:

``` java
Field f = ClassLoader.class.getDeclaredField("classes");
f.setAccessible(true);
Vector<Class> classes =  (Vector<Class>) f.get(lpparam.classLoader);
XposedBridge.log("*************** Loaded Class : " + classes.size() + " **************");
for (int i = classes.size() - 1; i >= 0; i--) {
    Class klass = classes.get(i);
    System.out.println(klass.getName());
}
```

this approach throws exception for the first line of code, `ClassLoader.class.getDeclaredField("classes")`
here is full exception:

``` java
java.lang.NoSuchFieldException: classes
    at java.lang.Class.getDeclaredField(Class.java:631)
    at spy.someapp.ir.someapp.Main.listLoadedClasses(Main.java:112)
    at spy.someapp.ir.someapp.Main.handleLoadPackage(Main.java:44)
    at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
    at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
    at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
    at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at android.app.ActivityThread.handleBindApplication(Native Method)
    at android.app.ActivityThread.access$1300(ActivityThread.java:141)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5041)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by rovo89** [comment]
Looks like you're using the wrong notation for your class name, use dots instead of slashes: http://api.xposed.info/reference/de/robv/android/xposed/XposedHelpers.html#findClass(java.lang.String,%20java.lang.ClassLoader)

As for your attempts to find out more: It's possible that the `PathClassLoader` (or whatever concrete class is used there) doesn't declare any fields itself. And `ClassLoader` doesn't have a field `classes`: https://android.googlesource.com/platform/libcore/+/android-6.0.1_r63/libart/src/main/java/java/lang/ClassLoader.java

**Comment by pashaie** [comment]
holy sh*t! I was so deep in smali code for deobfuscating, that I confused namespace notation completely. 
@rovo89 thanks man, you are a life saver!
