### ISSUE TITLE
SystemServer Crash caused by Resources Hook

### ISSUE THREAD

**Issue by aviraxp** [rovo89/XposedBridge#126]
It causes random soft reboot when booting and normally using, logs like this:

I am on Carndial AOSP (https://github.com/Cardinal-AOSP, MM based) running Xposed V86, disabling resources hook fixes it, but not a good method.

```
10-10 12:06:57.900  4454  4454 I SystemServer: Accessibility Manager

10-10 12:06:57.906  4454  4454 I XXXXXX  : choosing minFree values for 64 Bit

10-10 12:06:57.907  4454  4454 I XXXXXX  : choosing minFree values for 64 Bit

10-10 12:06:57.907  4454  4454 I XXXXXX  : choosing minFree values for 64 Bit

10-10 12:06:57.907  4454  4454 I XXXXXX  : choosing minFree values for 64 Bit

10-10 12:06:57.907  4454  4454 I XXXXXX  : choosing minFree values for 64 Bit

10-10 12:06:57.907  4454  4454 I XXXXXX  : choosing minFree values for 64 Bit

10-10 12:06:57.908  4454  4454 I ActivityManager: Config changes=1df8 {1.0 ?mcc?mnc zh_CN ldltr sw432dp w432dp h768dp 400dpi nrml long port ?uimode ?night -touch -keyb/v/h -nav/h s.2}

10-10 12:06:57.910  4454  4454 W SystemServer: ***********************************************

10-10 12:06:57.910  4454  4454 E SystemServer: BOOT FAILURE making display ready

10-10 12:06:57.910  4454  4454 E SystemServer: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

10-10 12:06:57.910  4454  4454 E SystemServer:  at android.app.ResourcesManager.applyConfigurationToResourcesLocked(ResourcesManager.java:300)

10-10 12:06:57.910  4454  4454 E SystemServer:  at android.app.ActivityThread.applyConfigurationToResources(ActivityThread.java:4226)

10-10 12:06:57.910  4454  4454 E SystemServer:  at com.android.server.am.ActivityManagerService.updateConfigurationLocked(ActivityManagerService.java:17557)

10-10 12:06:57.910  4454  4454 E SystemServer:  at com.android.server.am.ActivityManagerService.updateConfiguration(ActivityManagerService.java:17496)

10-10 12:06:57.910  4454  4454 E SystemServer:  at com.android.server.wm.WindowManagerService.displayReady(WindowManagerService.java:7668)

10-10 12:06:57.910  4454  4454 E SystemServer:  at com.android.server.SystemServer.startOtherServices(SystemServer.java:584)

10-10 12:06:57.910  4454  4454 E SystemServer:  at com.android.server.SystemServer.run(SystemServer.java:276)

10-10 12:06:57.910  4454  4454 E SystemServer:  at com.android.server.SystemServer.main(SystemServer.java:174)

10-10 12:06:57.910  4454  4454 E SystemServer:  at java.lang.reflect.Method.invoke(Native Method)

10-10 12:06:57.910  4454  4454 E SystemServer:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)

10-10 12:06:57.910  4454  4454 E SystemServer:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

10-10 12:06:57.910  4454  4454 E SystemServer:  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

10-10 12:06:57.912  4454  4454 I SystemServiceManager: Starting com.android.server.MountService$Lifecycle

10-10 12:06:57.923  4454  5236 D MountService: Thinking about reset, mSystemReady=false, mDaemonConnected=true

10-10 12:06:57.924  4454  5236 D MountService: Thinking about reset, mSystemReady=false, mDaemonConnected=true

10-10 12:06:57.925  4454  4454 I SystemServiceManager: Starting com.android.server.UiModeManagerService

10-10 12:06:57.927  4454  5236 D CryptdConnector: SND -> {1 cryptfs getfield SystemLocale}

10-10 12:06:57.928  4454  4454 I ActivityManager: Config changes=200 {1.0 ?mcc?mnc zh_CN ldltr sw432dp w432dp h768dp 400dpi nrml long port -touch -keyb/v/h -nav/h s.3}

10-10 12:06:57.929  4454  4454 E System  : ******************************************

10-10 12:06:57.930  4454  4454 E System  : ************ Failure starting system services

10-10 12:06:57.930  4454  4454 E System  : java.lang.RuntimeException: Failed to start service com.android.server.UiModeManagerService: onStart threw an exception

10-10 12:06:57.930  4454  4454 E System  :  at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:115)

10-10 12:06:57.930  4454  4454 E System  :  at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:104)

10-10 12:06:57.930  4454  4454 E System  :  at com.android.server.SystemServer.startOtherServices(SystemServer.java:608)

10-10 12:06:57.930  4454  4454 E System  :  at com.android.server.SystemServer.run(SystemServer.java:276)

10-10 12:06:57.930  4454  4454 E System  :  at com.android.server.SystemServer.main(SystemServer.java:174)

10-10 12:06:57.930  4454  4454 E System  :  at java.lang.reflect.Method.invoke(Native Method)

10-10 12:06:57.930  4454  4454 E System  :  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)

10-10 12:06:57.930  4454  4454 E System  :  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

10-10 12:06:57.930  4454  4454 E System  :  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

10-10 12:06:57.930  4454  4454 E System  : Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

10-10 12:06:57.930  4454  4454 E System  :  at android.app.ResourcesManager.applyConfigurationToResourcesLocked(ResourcesManager.java:300)

10-10 12:06:57.930  4454  4454 E System  :  at android.app.ActivityThread.applyConfigurationToResources(ActivityThread.java:4226)

10-10 12:06:57.930  4454  4454 E System  :  at com.android.server.am.ActivityManagerService.updateConfigurationLocked(ActivityManagerService.java:17557)

10-10 12:06:57.930  4454  4454 E System  :  at com.android.server.am.ActivityManagerService.updateConfiguration(ActivityManagerService.java:17496)

10-10 12:06:57.930  4454  4454 E System  :  at com.android.server.UiModeManagerService.sendConfigurationLocked(UiModeManagerService.java:396)

10-10 12:06:57.930  4454  4454 E System  :  at com.android.server.UiModeManagerService.onStart(UiModeManagerService.java:193)

10-10 12:06:57.930  4454  4454 E System  :  at com.android
[q.txt](https://github.com/rovo89/XposedBridge/files/518868/q.txt)
.server.SystemServiceManager.startService(SystemServiceManager.java:113)

10-10 12:06:57.930  4454  4454 E System  :  ... 8 more
```

**Comment by aviraxp** [comment]
Logs:

[q.txt](https://github.com/rovo89/XposedBridge/files/518869/q.txt)

**Comment by rovo89** [comment]
Why are you opening another issue for this???
#44
