### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by yoavst** [rovo89/XposedBridge#15]
When I try to call a static method from the class that declared as xposed class in xposed_init, it throw NoClassDefFoundError
The method is very simple:

``` java
public static void updateClocks() {
        XposedHelpers.callMethod(statusBarTextView, "updateClock");
        XposedHelpers.callMethod(insideTextView, "updateClock");
    }
```

**Comment by rovo89** [comment]
Your example is too short. I can't see where it crashes, how you initialize the variables, how you call the method etc. Please provide more context and also the full stacktrace of the exception.

**Comment by yoavst** [comment]
edit: source: https://github.com/yoavst/HebrewDate/tree/master
Stacktrace:
java.lang.NoClassDefFoundError: de.robv.android.xposed.XposedHelpers
            at com.yoavst.hebrewdatexposed.SettingsFragment.onSharedPreferenceChanged(SettingsFragment.java:34)
            at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:477)
            at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:385)
            at android.preference.Preference.tryCommit(Preference.java:1380)
            at android.preference.Preference.persistBoolean(Preference.java:1646)
            at android.preference.TwoStatePreference.setChecked(TwoStatePreference.java:84)
            at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:70)
            at android.preference.Preference.performClick(Preference.java:952)
            at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
            at android.widget.AdapterView.performItemClick(AdapterView.java:298)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1169)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
            at android.widget.AbsListView$4.run(AbsListView.java:3807)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5161)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by rovo89** [comment]
The answer is simple: You can't use the Xposed API in your app/activity, for many different reasons. The most important one is that these parts of your code run in different processes.

**Comment by yoavst** [comment]
Then i think you should write that on the wiki.
Do you have another idea how should i call a system method on event in the activity?
Because when i insert mPrefs.reload(); inside afterHookedMethod it doesn't find the preferences file!

**Comment by rovo89** [comment]
> Because when i insert mPrefs.reload(); inside afterHookedMethod it doesn't find the preferences file!

Same reason: It's in a different process. Your callbacks are basically injected into the app that you have hooked, so it runs with their user ID and can't access your settings unless you use MODE_WORLD_READBLE. Here is a module which uses that to reload settings every time an app is started: https://github.com/rovo89/AllAppsInPlayStore/tree/master/src/de/robv/android/xposed/mods/playstorefix

There are many things to write about the complex topic of different processes and all the limitations and solutions, but so far I didn't find the time and motivation to write another detailed explanation about that. I suggest you look at existing modules to learn, many are open-source.

**Comment by songwenhai** [comment]
Sorry, I have some question.

I know in a different process, they can't access other's settings unless using MODE_WORLD_READBLE. 

But why does NoClassDefFoundError occurs when I use the Xposed API, even when I use the class  declared in xposed_init. I think it's about classloader, not about process.

Thank you.

**Comment by rovo89** [comment]
I'm not sure I can follow. What are you trying to do? How do settings, the exception and xposed_init come together? They are quite different topics. Could you post the stack trace to make your point clearer?

**Comment by songwenhai** [comment]
Sorry, my last comment is confused.
Maybe this is a junior and stupid question. 
Now I know the reason.

In my module project, the class declared in xposed_init must implement interface from xposed.
But the classloader of my module's process didn't load xposed_bridge.jar,
so the classloader can't find the interface from xposed,
then classloader can't load the class implements interface from xposed.
So when I use this class, the NoClassDefFoundError occurs.

Thank you for your reply.

**Comment by rovo89** [comment]
Sorry, I still don't get it. The stack trace might be clearer.
If you're talking about your module's GUI, make sure that you don't have any direct or indirect references to the Xposed API in classes you reference from the GUI. If you need to share e.g. some constants between your GUI and the module code, it's a common pattern to create a Common.java file and reference to it from both.
