### ISSUE TITLE
getMethods is OK. findAndHookMethod has NoSuchMethod

### ISSUE THREAD

**Issue by chenfuzhi** [rovo89/XposedBridge#151]
```
        findAndHookMethod(Application.class, "attach", Context.class, new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                // place your hooks here, it should work with lpparam.classLoader
                XposedBridge.log("attach is ok");
                Context context = (Context) param.args[0];
                hookMultiClound(context, context.getClassLoader());
            }
        });
```

 ```
private void hookMultiClound(Context context, ClassLoader classLoader) {
        Class<?> QueryResult = null;

        try {
            QueryResult = classLoader.loadClass("com.XXXXXXXX.activity.QueryResult");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        XposedBridge.log("hookMultiClound");

        Method[] m = QueryResult.getMethods();
        for (final Method method : m) {
            //System.out.println(method.getName());
            XposedBridge.log("QueryResult methods: " + method.getName()); //this is ok
        }

        findAndHookMethod(QueryResult, "onCreate", Context.class, new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                // place your hooks here, it should work with lpparam.classLoader
                XposedBridge.log("QueryResult     onCreate.........");
            }
        });
```

app dex2jar's jar    jd-GUI 

```
package com.secneo.apkwrapper;

import android.app.Application;
import android.content.Context;
import android.content.res.Configuration;
import android.os.Build;
import android.util.ArrayMap;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Iterator;
import java.util.Map.Entry;
import java.util.Set;

public class ApplicationWrapper
  extends Application
{
  public static Application realApplication = null;
  
  static
  {
    System.loadLibrary("DexHelper");
    if (Helper.PPATH != null) {
      System.load(Helper.PPATH);
    }
  }
  
  protected void attachBaseContext(Context paramContext)
  {
    super.attachBaseContext(paramContext);
    try
    {
      realApplication = (Application)getClassLoader().loadClass(Helper.APPNAME).newInstance();
      Helper.attach(realApplication, paramContext);
      return;
    }
    catch (Exception paramContext)
    {
      realApplication = null;
    }
  }
  
```

error log:

```
attach is ok
01-12 00:59:01.085 I/Xposed  ( 3252): hookMultiClound
01-12 00:59:01.086 E/Xposed  ( 3252): java.lang.NoSuchMethodError: xxxxxxxxxx.flight.activity.QueryResult#onCreate(android.content.Context)#exact
01-12 00:59:01.086 E/Xposed  ( 3252): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:330)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:182)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at test.xposed.xposedtest.RedClock.hookMultiClound(RedClock.java:97)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at test.xposed.xposedtest.RedClock.access$000(RedClock.java:27)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at test.xposed.xposedtest.RedClock$2.afterHookedMethod(RedClock.java:58)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at android.app.Application.attach(<Xposed>)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at android.app.Instrumentation.newApplication(Instrumentation.java:998)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at android.app.Instrumentation.newApplication(Instrumentation.java:982)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:574)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4729)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at android.os.Looper.loop(Looper.java:148)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at android.app.ActivityThread.main(ActivityThread.java:5466)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at java.lang.reflect.Method.invoke(Native Method)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-12 00:59:01.086 E/Xposed  ( 3252): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java
```

How to solve this problem？thanks

**Comment by rovo89** [comment]
`getMethods()` includes methods that are inherited from the super class. `findAndHookMethod()` uses `getDeclaredMethods()` to get only methods that are declared exactly for the class you're hooking. Why?
http://api.xposed.info/reference/de/robv/android/xposed/XposedHelpers.html#findAndHookMethod(java.lang.String,%20java.lang.ClassLoader,%20java.lang.String,%20java.lang.Object...)

**Comment by chenfuzhi** [comment]
thanks @rovo89 I find the problem

THANKS A LOT

**Comment by EricMo** [comment]
The same probleam with u.
error log:
```
java.lang.NoSuchMethodError: com.XXXX.XXXX.XXXX.XXXX.adapter.MessageChatAdapter#a(com.XXXX.XXXX.XXXX.model.ChattingModel,java.lang.Integer,android.view.ViewGroup)#exact
                                             at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
                                             at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
                                             at com.conch.bluedhook.MainModule.hookMultiClass(MainModule.java:60)
                                             at com.conch.bluedhook.MainModule.access$000(MainModule.java:22)
                                             at com.conch.bluedhook.MainModule$1.afterHookedMethod(MainModule.java:33)
                                             at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
                                             at android.app.Application.attach(Native Method)
                                             at android.app.Instrumentation.newApplication(Instrumentation.java)
                                             at android.app.Instrumentation.newApplication(Instrumentation.java)
                                             at android.app.LoadedApk.makeApplication(LoadedApk.java)
                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
                                             at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                             at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
                                             at android.app.ActivityThread.handleBindApplication(Native Method)
                                             at android.app.ActivityThread.access$1500(ActivityThread.java)
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
                                             at android.os.Handler.dispatchMessage(Handler.java)
                                             at android.os.Looper.loop(Looper.java)
                                             at android.app.ActivityThread.main(ActivityThread.java)
                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                                             at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                                             at dalvik.system.NativeStart.main(Native Method)
```

and this code:
```java
    @SuppressLint({ "InflateParams" })
    private View a(final ChattingModel chattingModel, final int n, final ViewGroup viewGroup) {
        final short msgType = chattingModel.msgType;
       if (MsgType.getClassify(msgType) == 1 || msgType == 26) {
            return this.c.inflate(2130968945, viewGroup, false);
        }
        if (MsgType.getGroupOperationNotifyType(msgType) == 2) {
            return this.c.inflate(2130968922, viewGroup, false);
        }}
```

**Comment by rovo89** [comment]
@EricMo The type is `int`, so you have to use `int.class`, not `Integer.class`.
