### ISSUE TITLE
hook too many classes led to the start of the WeChat crash

### ISSUE THREAD

**Issue by qssq666123** [rovo89/XposedBridge#155]
I try to use the tool to automate the hook of all classes of a app, so I know what kind of hook class each click
The app is a huge wechat project,
Because hook too many classes led to the start of the WeChat crash

```
E/dalvikvm( 7238): JNI ERROR (app bug): global reference table overflow (max=51200)
W/dalvikvm( 7238): JNI global reference table (0x7c737010) dump:
W/dalvikvm( 7238):   Last 10 entries (of 51200):
W/dalvikvm( 7238):     51199: 0x964305a8 java.lang.reflect.Method
W/dalvikvm( 7238):     51198: 0x9642ff78 de.robv.android.xposed.XposedBridge$AdditionalHookInfo
W/dalvikvm( 7238):     51197: 0x9642ef28 java.lang.reflect.Method
W/dalvikvm( 7238):     51196: 0x9642e650 de.robv.android.xposed.XposedBridge$AdditionalHookInfo
W/dalvikvm( 7238):     51195: 0x9642db40 java.lang.reflect.Method
W/dalvikvm( 7238):     51194: 0x9642d518 de.robv.android.xposed.XposedBridge$AdditionalHookInfo
W/dalvikvm( 7238):     51193: 0x96420b58 java.lang.reflect.Method
W/dalvikvm( 7238):     51192: 0x9642c2b8 de.robv.android.xposed.XposedBridge$AdditionalHookInfo
W/dalvikvm( 7238):     51191: 0x9642b878 java.lang.reflect.Method
W/dalvikvm( 7238):     51190: 0x96421828 de.robv.android.xposed.XposedBridge$AdditionalHookInfo
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.friend.e$2
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.friend.e$3
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.friend.g
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.friend.h$1
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.friend.h
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.friend.i
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.g$10
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.g$13
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.g$14
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.g$4
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.g$5
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.g$8
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.g$9
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.g.b
D/HookAllMethodCall( 7427): find-fail-抽象的类 com.tencent.mm.ui.h
D/HookAllMethodCall( 7427): find-fail-抽象的类 com.tencent.mm.ui.j
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.k$1
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.k$9
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.l
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.mogic.WxViewPager$SavedState$1
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.mogic.WxViewPager$c
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.p$1
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.p$2
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.r$1
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.r$2
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.r$3
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.snackbar.a$1
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.t
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.tools.ActionBarSearchView$7
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.tools.ActionBarSearchView
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.tools.CountryCodeUI$3
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.tools.CountryCodeUI$4
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.tools.CountryCodeUI$5
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.tools.CropImageNewUI$12
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.tools.CropImageNewUI$13
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.tools.CropImageNewUI$14
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.tools.CropImageNewUI$20$1
W/HookAllMethodCall( 7427): find-succcom.tencent.mm.ui.tools.CropImageNewUI$20$2
E/dalvikvm( 7427): JNI ERROR (app bug): global reference table overflow (max=51200)
W/dalvikvm( 7427): JNI global reference table (0x7de18010) dump:
W/dalvikvm( 7427):   Last 10 entries (of 51200):
W/dalvikvm( 7427):     51199: 0x9646e2f0 java.lang.reflect.Method
W/dalvikvm( 7427):     51198: 0x9646b4b0 de.robv.android.xposed.XposedBridge$AdditionalHookInfo
W/dalvikvm( 7427):     51197: 0x964544f0 java.lang.reflect.Method
W/dalvikvm( 7427):     51196: 0x9632ad70 de.robv.android.xposed.XposedBridge$AdditionalHookInfo
W/dalvikvm( 7427):     51195: 0x962c7830 java.lang.reflect.Method
W/dalvikvm( 7427):     51194: 0x962c7648 de.robv.android.xposed.XposedBridge$AdditionalHookInfo
W/dalvikvm( 7427):     51193: 0x96284ac8 java.lang.reflect.Method
W/dalvikvm( 7427):     51192: 0x9621f818 de.robv.android.xposed.XposedBridge$AdditionalHookInfo
W/dalvikvm( 7427):     51191: 0x96142bd8 java.lang.reflect.Method
W/dalvikvm( 7427):     51190: 0x961bb030 de.robv.android.xposed.XposedBridge$AdditionalHookInfo
W/dalvikvm( 7427):   Summary:
W/dalvikvm( 7427):       225 of java.lang.Class (193 unique instances)
W/dalvikvm( 7427):         2 of java.lang.String (2 unique instances)
W/dalvikvm( 7427):         4 of java.lang.reflect.Constructor (4 unique instances)
W/dalvikvm( 7427):     25467 of java.lang.reflect.Method (25467 unique instances)
W/dalvikvm( 7427):        11 of java.lang.ref.WeakReference (11 unique instances)
W/dalvikvm( 7427):         1 of android.app.ActivityThread$ApplicationThread
W/dalvikvm( 7427):     25470 of de.robv.android.xposed.XposedBridge$AdditionalHookInfo (25470 unique instances)
W/dalvikvm( 7427):         1 of android.hardware.display.DisplayManagerGlobal$DisplayManagerCallback
W/dalvikvm( 7427):         4 of android.app.LoadedApk$ReceiverDispatcher$InnerReceiver (4 unique instances)
W/dalvikvm( 7427):        11 of android.content.ContentProvider$Transport (11 unique instances)
W/dalvikvm( 7427):         1 of android.opengl.EGLDisplay
W/dalvikvm( 7427):         1 of android.opengl.EGLContext
W/dalvikvm( 7427):         1 of android.opengl.EGLSurface
W/dalvikvm( 7427):         1 of android.telephony.PhoneStateListener$1
E/dalvikvm( 7427): Failed adding to JNI global ref table (51200 entries)
I/dalvikvm( 7427): "main" prio=5 tid=1 RUNNABLE
I/dalvikvm( 7427):   | group="main" sCount=0 dsCount=0 obj=0x94cfbbd8 self=0xb8d425e0
I/dalvikvm( 7427):   | sysTid=7427 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=-1216645408
I/dalvikvm( 7427):   | state=R schedstat=( 0 0 0 ) utm=694 stm=226 core=0
I/dalvikvm( 7427):   at de.robv.android.xposed.XposedBridge.hookMethodNative(Native Method)
I/dalvikvm( 7427):   at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:539)
I/dalvikvm( 7427):   at cn.qssq666.stringhook.XposeUtils.hookAllMethod(XposeUtils.java:175)
I/dalvikvm( 7427):   at cn.qssq666.stringhook.XposeUtils.access$000(XposeUtils.java:30)
I/dalvikvm( 7427):   at cn.qssq666.stringhook.XposeUtils$1.afterHookedMethod(XposeUtils.java:43)
I/dalvikvm( 7427):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:645)
I/dalvikvm( 7427):   at android.app.Application.onCreate(Native Method)
I/dalvikvm( 7427):   at com.tencent.tinker.loader.app.TinkerApplication.onCreate(SourceFile:171)
I/dalvikvm( 7427):   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
I/dalvikvm( 7427):   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
I/dalvikvm( 7427):   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
I/dalvikvm( 7427):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
I/dalvikvm( 7427):   at android.app.ActivityThread.handleBindApplication(Native Method)
I/dalvikvm( 7427):   at android.app.ActivityThread.access$1500(ActivityThread.java:135)
I/dalvikvm( 7427):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
I/dalvikvm( 7427):   at android.os.Handler.dispatchMessage(Handler.java:102)
I/dalvikvm( 7427):   at android.os.Looper.loop(Looper.java:136)
I/dalvikvm( 7427):   at android.app.ActivityThread.main(ActivityThread.java:5045)
I/dalvikvm( 7427):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm( 7427):   at java.lang.reflect.Method.invoke(Method.java:515)
I/dalvikvm( 7427):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
I/dalvikvm( 7427):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
I/dalvikvm( 7427):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
I/dalvikvm( 7427):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm( 7427): 
E/dalvikvm( 7427): VM aborting
F/libc    ( 7427): Fatal signal 6 (SIGABRT) at 0x00001d03 (code=-6), thread 7427 (com.tencent.mm)
I/DEBUG   ( 3052): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   ( 3052): Build fingerprint: 'Android/samsung/samsung:4.4.2/KOT49H/3.8.0.0120:userdebug/test-keys'
I/DEBUG   ( 3052): Revision: '0'
I/DEBUG   ( 3052): pid: 7427, tid: 7427, name: com.tencent.mm  >>> com.tencent.mm <<<
I/DEBUG   ( 3052): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
I/DEBUG   ( 3052):     eax 00000000  ebx 00001d03  ecx 00001d03  edx 00000006
I/DEBUG   ( 3052):     esi 00001d03  edi 00000002
I/DEBUG   ( 3052):     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
I/DEBUG   ( 3052):     eip b7706dc6  ebp b776ece0  esp bffe8b60  flags 00200203
I/DEBUG   ( 3052): 
I/DEBUG   ( 3052): backtrace:
I/DEBUG   ( 3052):     #00  pc 0003bdc6  /system/lib/libc.so
I/DEBUG   ( 3052):     #01  pc 00000005  <unknown>
I/DEBUG   ( 3052): 
I/DEBUG   ( 3052): stack:
I/DEBUG   ( 3052):          bffe8b20  00000000  
I/DEBUG   ( 3052):          bffe8b24  b776a268  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b28  00000000  
I/DEBUG   ( 3052):          bffe8b2c  b76d8f39  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b30  b776a18c  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b34  b8dd31e0  [heap]
I/DEBUG   ( 3052):          bffe8b38  00000015  
I/DEBUG   ( 3052):          bffe8b3c  b4da200a  /system/lib/libdvm.so
I/DEBUG   ( 3052):          bffe8b40  00000000  
I/DEBUG   ( 3052):          bffe8b44  b7725616  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b48  b7769fcc  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b4c  b7710cf6  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b50  00000000  
I/DEBUG   ( 3052):          bffe8b54  00000000  
I/DEBUG   ( 3052):          bffe8b58  b76d8d69  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b5c  b7769fcc  /system/lib/libc.so
I/DEBUG   ( 3052):     #00  bffe8b60  00000006  
I/DEBUG   ( 3052):          bffe8b64  00001d03  
I/DEBUG   ( 3052):          bffe8b68  b7769fcc  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b6c  b76e34a6  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b70  00001d03  
I/DEBUG   ( 3052):          bffe8b74  00001d03  
I/DEBUG   ( 3052):          bffe8b78  00000006  
I/DEBUG   ( 3052):          bffe8b7c  00000000  
I/DEBUG   ( 3052):          bffe8b80  b776a268  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b84  00000000  
I/DEBUG   ( 3052):          bffe8b88  b76e3449  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b8c  b7769fcc  /system/lib/libc.so
I/DEBUG   ( 3052):          bffe8b90  bffe8bdc  [stack]
I/DEBUG   ( 3052):          bffe8b94  bffe8e10  [stack]
I/DEBUG   ( 3052):          bffe8b98  b4f6cbf4  
I/DEBUG   ( 3052):          bffe8b9c  b76e382c  /system/lib/libc.so
I/BootReceiver( 5905): Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
D/dalvikvm( 5905): GC_FOR_ALLOC freed 1338K, 19% free 9055K/11124K, paused 13ms, total 13ms
D/Zygote  ( 5623): Process 7427 terminated by signal (6)
I/ActivityManager( 5905): Process com.tencent.mm (pid 7427) has died.
D/dalvikvm( 5905): GC_FOR_ALLOC freed 204K, 16% free 9344K/11124K, paused 13ms, total 14ms
I/ActivityManager( 5905): Start proc com.tencent.mm for activity com.tencent.mm/.ui.LauncherUI: pid=7682 uid=10047 gids={50047, 3003, 1028, 1015, 1023, 3002, 3001}
D/dalvikvm( 5905): GC_FOR_ALLOC freed 28K, 15% free 9508K/11124K, paused 15ms, total 15ms
I/dalvikvm-heap( 5905): Grow heap (frag case) to 9.883MB for 293056-byte allocation
D/dalvikvm( 5905): GC_FOR_ALLOC freed 190K, 16% free 9604K/11412K, paused 12ms, total 12ms
D/dalvikvm( 5905): GC_FOR_ALLOC freed 582K, 20% free 9220K/11412K, paused 13ms, total 13ms
W/NetworkManagementSocketTagger( 5905): setKernelCountSet(10047, 0) failed with errno -13
W/NetworkManagementSocketTagger( 5905): setKernelCountSet(10047, 1) failed with errno -13
I/Xposed  ( 7682): qssq_pro :handleLoadPackage->com.tencent.mm
I/Xposed  ( 7682): qssq_pro :memoryCache1cn.qssq666.pro.redpackaget.bean.MemoryCache@4a7c96a8,null,false
I/Xposed  ( 7682): qssq_pro :classTheread:class android.app.ActivityThread
W/WindowManager( 5905): updateFocusedWindowLocked, focusedAppToken is null.
I/Xposed  ( 7682): qssq_pro :initContext->packageName:,android.app.ContextImpl@4a85d6a0,android.app.ContextImpl@4a85d6a0
I/Xposed  ( 7682): qssq_pro :memoryCachecn.qssq666.pro.redpackaget.bean.MemoryCache@4a7c96a8,android.app.ContextImpl@4a85d6a0,false
I/Xposed  ( 7682): qssq_pro :wechat1000
I/Xposed  ( 7682): qssq_pro :reg new regsettingReceiver->null,contextandroid.app.ContextImpl@4a85d6a0,wechat->cn.qssq666.pro.redpackaget.bean.WeChatConfig@4a7c96f8
I/Xposed  ( 7682): qssq_pro :wechatname:com.tencent.mm,vercode:1000
I/Xposed  ( 7682): qssq_pro :->1000 QSSQUtilsluckcom.tencent.mm.plugin.luckymoney.c.ab,com.tencent.mm.model.ak,class_3_getNetWordModelMethodvy,com.tencent.mm.e.b.by,b,com.tencent.mm.sdk.platformtools.be,kykS,com.tencent.mm.booter.notification.c,com.tencent.mm.h.i
I/Xposed  ( 7682): qssq_pro :starthandleLoadPackage com.tencent.mm-end
I/Xposed  ( 7682): context:android.app.ContextImpl@4a85d6a0
D/dalvikvm( 7682): JIT code cache reset in 0 ms (0 bytes 2/0)
D/dalvikvm( 7682): GC_FOR_ALLOC freed 369K, 17% free 3642K/4340K, paused 5ms, total 5ms
D/dalvikvm( 7682): GC_FOR_ALLOC freed 200K, 12% free 3953K/4476K, paused 4ms, total 4ms
D/dalvikvm( 7682): GC_FOR_ALLOC freed 116K, 10% free 4342K/4788K, paused 5ms, total 5ms
D/dalvikvm( 7682): GC_FOR_ALLOC freed 112K, 9% free 4723K/5176K, paused 6ms, total 6ms
D/dalvikvm( 7682): GC_FOR_ALLOC freed 130K, 9% free 5081K/5556K, paused 5ms, total 5ms
I/dalvikvm( 7682): Could not find method android.app.ActivityManager.getAppTasks, referenced from method com.tencent.mm.sdk.platformtools.bf.eh
W/dalvikvm( 7682): VFY: unable to resolve virtual method 172: Landroid/app/ActivityManager;.getAppTasks ()Ljava/util/List;
D/dalvikvm( 7682): VFY: replacing opcode 0x6e at 0x0011
D/dalvikvm( 7682): DexOpt: couldn't find field Landroid/app/ActivityManager$RecentTaskInfo;.topActivity
I/dalvikvm( 7682): DexOpt: unable to optimize instance field ref 0x002c at 0x35 in Lcom/tencent/mm/sdk/platformtools/bf;.eh
D/dalvikvm( 7682): GC_FOR_ALLOC freed 384K, 13% free 5197K/5924K, paused 6ms, total 6ms
D/dalvikvm( 7682): GC_FOR_ALLOC freed 1437K, 30% free 4294K/6084K, paused 5ms, total 5ms
D/dalvikvm( 7682): GC_FOR_ALLOC freed <1K, 21% free 4806K/6084K, paused 4ms, total 4ms
D/dalvikvm( 7682): GC_FOR_ALLOC freed 60K, 15% free 5213K/6084K, paused 4ms, total 4ms
D/dalvikvm( 7682): GC_FOR_ALLOC freed 30K, 15% free 5228K/6084K, paused 6ms, total 6ms
I/dalvikvm-heap( 7682): Grow heap (frag case) to 5.485MB for 69748-byte allocation
D/dalvikvm( 7682): GC_FOR_ALLOC freed 92K, 16% free 5203K/6156K, paused 5ms, total 5ms
W/HookAllMethodCall( 7682): find-succMTT.ThirdAppInfoNew
D/HookAllMethodCall( 7682): find-fail-抽象的类 a.a.a.a.a.b
W/HookAllMethodCall( 7682): find-succa.a.a.a.a
W/HookAllMethodCall( 7682): find-succa.a.a.a
W/HookAllMethodCall( 7682): find-succa.a.a.b.a.a
W/HookAllMethodCall( 7682): find-succa.a.a.b.a.b
W/HookAllMethodCall( 7682): find-succa.a.a.b.a
W/HookAllMethodCall( 7682): find-succa.a.a.b.b.a
W/HookAllMethodCall( 7682): find-succa.a.a.b
W/HookAllMethodCall( 7682): find-succa.a.a.c.a
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.a
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.b$1
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.b$a
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.b$b
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.c$a
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.c$b
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.c
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.d
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.b.a.e
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.f$c
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.f$d
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.f$e
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.f$f
W/HookAllMethodCall( 7682): find-succandroid.support.b.a.f$g
W/HookAllMethodCall( 7682): find-succandroid.support.design.a$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.a$b
W/HookAllMethodCall( 7682): find-succandroid.support.design.a$c
W/HookAllMethodCall( 7682): find-succandroid.support.design.a$d
W/HookAllMethodCall( 7682): find-succandroid.support.design.a$e
W/HookAllMethodCall( 7682): find-succandroid.support.design.a$f
W/HookAllMethodCall( 7682): find-succandroid.support.design.a$g
W/HookAllMethodCall( 7682): find-succandroid.support.design.a$h
W/HookAllMethodCall( 7682): find-succandroid.support.design.a$i
W/HookAllMethodCall( 7682): find-succandroid.support.design.a
W/HookAllMethodCall( 7682): find-succandroid.support.design.internal.ParcelableSparseArray
W/HookAllMethodCall( 7682): find-succandroid.support.design.internal.ScrimInsetsFrameLayout
W/HookAllMethodCall( 7682): find-succandroid.support.design.internal.b$1
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.internal.b$d
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.AppBarLayout$Behavior$SavedState
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.AppBarLayout$Behavior$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.AppBarLayout$LayoutParams
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.AppBarLayout$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.AppBarLayout
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.BottomSheetBehavior$SavedState$1
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.BottomSheetBehavior$SavedState
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.BottomSheetBehavior$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.BottomSheetBehavior$b
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.CollapsingToolbarLayout$LayoutParams
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.CollapsingToolbarLayout
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.CoordinatorLayout$1
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.CoordinatorLayout$Behavior
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.CoordinatorLayout$SavedState
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.CoordinatorLayout$b
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.CoordinatorLayout$c
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.CoordinatorLayout$d
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.CoordinatorLayout$e
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.CoordinatorLayout$f
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.HeaderBehavior$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.NavigationView$SavedState
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.NavigationView$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.Snackbar$1
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.Snackbar$2
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.Snackbar$4$1
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.Snackbar$7
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.Snackbar$SnackbarLayout$a
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.Snackbar$SnackbarLayout$b
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.Snackbar$SnackbarLayout
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.Snackbar
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.TabItem
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.TabLayout$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.TabLayout$b
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.TabLayout$c
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.TabLayout
D/dalvikvm( 7682): JIT code cache reset in 0 ms (0 bytes 3/0)
D/dalvikvm( 7682): GC_FOR_ALLOC freed 409K, 13% free 5360K/6156K, paused 5ms, total 5ms
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.TextInputLayout$1
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.TextInputLayout$SavedState$1
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.TextInputLayout$SavedState
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.TextInputLayout
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.VisibilityAwareImageButton
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.a
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.aa$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.aa
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.b
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.c$1
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.d
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.f
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.g
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.i
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.j$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.k$1
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.k$2
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.l$1
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.l$a
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.l
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.n
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.p
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.q$1
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.q$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.q$b
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.q
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.r$1
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.r$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.r
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.s$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.s$b
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.t
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.u$a
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.u$c
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.u$d
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.u$e$a
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.u$e$b
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.u$e
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.u
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.v$1
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.w$1
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.w$2
D/HookAllMethodCall( 7682): find-fail-抽象的类 android.support.design.widget.x$a
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.x
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.y
W/HookAllMethodCall( 7682): find-succandroid.support.design.widget.z[](url)
```

**Comment by rovo89** [comment]
Yeah, there is some limit, as the global reference table is limited to 51200 entries. Xposed uses global references to avoid that some objects related to the hooks/callbacks don't get garbage collected. I might be able to use a different way on ART, but I don't think I could do that for Dalvik.

But really, 25k hooks isn't the core use-case for Xposed. For your purpose, you should rather look for a method tracer. A quick Google search shows several options, although I don't know which ones are the best.

**Comment by qssq666123** [comment]
Well, there is no other way to monitor the behavior of all classes of the app call

**Comment by rovo89** [comment]
And if you hook all methods of all classes, you think you can find out how the app behaves? ;) Try to be more targeted, i.e. hook exactly those methods you're interested in and get stack traces from them. Or use a dedicated method tracer, like I said.

**Comment by qssq666123** [comment]
if  can do all the monitoring method, it can be more convenient to track any program, convenient, easy to watch, you can help us to quickly analyze which should be hook, so that I can develop a dynamic tracking tool without the need to unpack the program. I think that if the realization of a lot of efficiency, I hope you can help me solve this problem
If you can dynamically monitor it will promote a new wave of hook

**Comment by qssq666123** [comment]
Because of the huge program analysis is very tired, the efficiency is very low
It is difficult to develop a hook plug-in with my current technology

**Comment by rovo89** [comment]
I don't think Xposed is the right platform to to build a tool that analyzes the flow of a whole app. I don't really know what you want to analyze, not sure if you do. Logging every method call (including things like `Object.equals()`) will be slow, won't be possible with Xposed (because you must not hook such central methods anyway) and might not even help you to reach your goal. If you get list with thousands of calls, which one would you look at? That's why I said, don't try to log all the data, but be more targeted.

I'll close this issue here. I don't think that avoiding global references in order to remove this limiation would help you, for the reasons I mentioned above.
