### ISSUE TITLE
Cannot read/write sdcard in my Xposed module!!!!

### ISSUE THREAD

**Issue by lzq8272587** [rovo89/XposedBridge#168]
Hello everyone!

Recently I am using Xposed to log the inter-component calls such as startService/bindService in my Android device.

What I did is to write down a record in sdcard if startService() or bindSerivce() is called.

I can successfully hook the call, but when I try to read/write a new record in the sdcard, I always get the error:

```
05-01 16:20:20.609 1029-10028/? E/Xposed: java.io.FileNotFoundException: /data/local/tmp/log: open failed: EACCES (Permission denied)
     at libcore.io.IoBridge.open(IoBridge.java:452)
     at java.io.FileInputStream.<init>(FileInputStream.java:76)
     at java.io.FileReader.<init>(FileReader.java:42)
     at com.netlab.actfreezer.SystemServiceHook$BindServiceContextHook.beforeHookedMethod(SystemServiceHook.java:327)
     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
     at com.android.server.am.ActivityManagerService.bindService(<Xposed>)
     at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:985)
     at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2489)
     at android.os.Binder.execTransact(Binder.java:453)
  Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
     at libcore.io.Posix.open(Native Method)
     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
     at libcore.io.IoBridge.open(IoBridge.java:438)
     at java.io.FileInputStream.<init>(FileInputStream.java:76) 
     at java.io.FileReader.<init>(FileReader.java:42) 
     at com.netlab.actfreezer.SystemServiceHook$BindServiceContextHook.beforeHookedMethod(SystemServiceHook.java:327) 
     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314) 
     at com.android.server.am.ActivityManagerService.bindService(<Xposed>) 
     at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:985) 
     at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2489) 
     at android.os.Binder.execTransact(Binder.java:453) 
```

It seems that my Xposed module does not have the permission to read/write sdcard.

But I grant the storage permission in the Manifest of my Xposed module app, and also in the Xposed installer. My device is rooted, and the default setting in my Super SU is to grant root permission for any request.

How can I fix the problem? Thanks !!

**Comment by aviraxp** [comment]
system_server does not have the permission to access sdcard.

**Comment by rovo89** [comment]
That's right. The module's manifest doesn't matter here, it only applies to the app itself. Hooks are executed in the process of the hooked method, so the permissions of that process apply.

**Comment by aviraxp** [comment]
Just a note, you can use /data/system, as it is the place for system to store files.

**Comment by lzq8272587** [comment]
Hi Wang:

Thank you very much, it works when I change the path to /data/system.

Just for curious:

(1) is it possible for me to grant storage read/write permission to the the system_server process?

(2) actually, I want to deliver data between my Xposed module and another app. Beside delivering data via a file on disk, are there any other approaches to accomplish the goal?

Many thanks again!

Best,

**Comment by aviraxp** [comment]
1. I don't think so. system_server does not match the SELinux context for sdcard, nor does it has the permission to handle it.

2. I guess you can use content provider to do such things, which is designed to pass data through different process. You can also use broadcast and put the data on extras I think (but you need to find the accurate context). You can also try using IPCs.

**Comment by lzq8272587** [comment]
Hmm, but I cannot get an application context to use content provider or send broadcasts in the Xposed module.

Let me find other solutions. Thanks!

**Comment by aviraxp** [comment]
You can get almost every context by Xposed. See this:

https://github.com/AdBlocker-Reborn/AdBlocker_Reborn/blob/master/app/src/main/java/com/aviraxp/adblocker/continued/util/ContextUtils.java

https://github.com/AdBlocker-Reborn/AdBlocker_Reborn/blob/master/app/src/main/java/android/app/ActivityThread.java

**Comment by lzq8272587** [comment]
oops, does it mean to hook an application so that I can get its context? Thus I can send broadcasts.

**Comment by 1ultimat3** [comment]
Have you found a solution? I am facing a similar issue: a dependency wants to create a temp file...
