### ISSUE TITLE
Intent for main activity

### ISSUE THREAD

**Issue by daimoniuma** [rovo89/XposedBridge#171]
I'm trying to change startup fragment. There is onCreate from main activity:
```
  public void onCreate(Bundle paramBundle)
  {
    boolean bool = false;
    super.onCreate(paramBundle);
    Object localObject = Analytics.getInstance();
    if (paramBundle == null) {
      bool = true;
    }
    ((Analytics)localObject).enableCheckForUpdates(bool);
    localObject = new FitSystemWindowsFragmentWrapperFrameLayout(this);
    ((FrameLayout)localObject).setId(2131755051);
    if (Build.VERSION.SDK_INT >= 21) {
      ((FrameLayout)localObject).setFitsSystemWindows(true);
    }
    getNavigationDelegate().setContentView((View)localObject);
    if (AccountManager.getCurrent().isReal())
    {
      ShortcutManagerWrapper.getInstance().ensureShortcuts(this);
      if (getIntent().hasExtra("class")) {
        FragmentHelper.replace(this, (Class)getIntent().getSerializableExtra("class"), getIntent().getBundleExtra("args"), getNavigationDelegate());
      }
    }
```
There is what I tried:
```
XposedHelpers.findAndHookMethod("xxx.MainActivity", lpparam.classLoader, "onCreate", Bundle.class, new XC_MethodHook() {
				@Override
				protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
					Class<?> mainActivity = XposedHelpers.findClass("xxx.MainActivity", lpparam.classLoader);
					Class<?> dialogsFragment = XposedHelpers.findClass("xxx.DialogsFragment", lpparam.classLoader);
					Intent intent = new Intent(context, mainActivity);
					intent.putExtra("class", dialogsFragment);
					Bundle startupBundle = new Bundle();
					intent.putExtra("args", startupBundle);
					???
				}
```
Context from @aviraxp implementation:
`context = ContextUtils.getOwnContext();`

How to push it? 😅

**Comment by rovo89** [comment]
I don't get the question, what do you want to do? Do you want to replace the intent that is used in the last line (the one with `FragmentHelper.replace(...)`)? Then you might want to call https://developer.android.com/reference/android/app/Activity.html#setIntent(android.content.Intent) for this, or manipulate the object returned by `getIntent()` instead of creating a new instance.

By the way, an `Activity` **is** a `Context`, so you could maybe just use `param.thisObject` when you need a context.

**Comment by daimoniuma** [comment]
Yes, it should be launcher intent. FragmentHelper.replace is used for shortcuts, I guess. I want to try to set needed class to change startup fragment in that app. Sorry, how to getIntent? Could param.thisObject be casted to context?

**Comment by rovo89** [comment]
Yeah, `param.thisObject` is the `MainActivity` instance, so you can do with it whatever you can do with an `Activity`.

**Comment by daimoniuma** [comment]
Holy, it works! I'm so happy. 😊
But I did something wrong.
1. Launcher intent is going to main activity.
2. Before onCreate I created new intent.
```
                                        Class<?> mainActivity = XposedHelpers.findClass("...MainActivity", lpparam.classLoader);
					Class<?> dialogsFragment = XposedHelpers.findClass("...DialogsFragment", lpparam.classLoader);
					Context activityContext = (Context) param.thisObject;
					Intent intent = new Intent(activityContext, mainActivity);
					intent.putExtra("class", dialogsFragment);
					//Bundle startupBundle = new Bundle();
					//intent.putExtra("args", startupBundle);
					activityContext.startActivity(intent, null);
```
But I got ultimately long opening. At the end it loads defined fragment, then crashes.
Please, correct me. I don't know how to getIntent/setIntent under Xposed.
```
java.lang.OutOfMemoryError: Failed to allocate a 483852 byte allocation with 366308 free bytes and 357KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:761)
	at com.vkontakte.android.ui.DialogEntryView.onDraw(DialogEntryView.java:629)
	at android.view.View.draw(View.java:15171)
	at android.view.View.updateDisplayListIfDirty(View.java:14096)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4400)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at me.grishka.appkit.views.UsableRecyclerView.dispatchDraw(UsableRecyclerView.java:314)
	at android.view.View.draw(View.java:15174)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3792)
	at android.view.View.updateDisplayListIfDirty(View.java:14096)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1195)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at android.view.View.updateDisplayListIfDirty(View.java:14091)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at android.view.View.updateDisplayListIfDirty(View.java:14091)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at android.view.View.updateDisplayListIfDirty(View.java:14091)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at android.view.View.updateDisplayListIfDirty(View.java:14091)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at android.view.View.updateDisplayListIfDirty(View.java:14091)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at com.vkontakte.android.ui.FitSystemWindowsFragmentWrapperFrameLayout.dispatchDraw(FitSystemWindowsFragmentWrapperFrameLayout.java:55)
	at android.view.View.updateDisplayListIfDirty(View.java:14091)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at android.view.View.draw(View.java:15174)
	at android.view.View.updateDisplayListIfDirty(View.java:14096)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at android.view.View.updateDisplayListIfDirty(View.java:14091)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at android.view.View.updateDisplayListIfDirty(View.java:14091)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at android.view.View.updateDisplayListIfDirty(View.java:14091)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at android.view.View.updateDisplayListIfDirty(View.java:14091)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.View.draw(View.java:14895)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3407)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3201)
	at android.view.View.draw(View.java:15174)
	at android.widget.FrameLayout.draw(FrameLayout.java:592)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2695)
	at android.view.View.updateDisplayListIfDirty(View.java:14096)
	at android.view.View.getDisplayList(View.java:14119)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2531)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2367)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1998)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5356)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by daimoniuma** [comment]
In fact I just need to stick `intent.putExtra("class", dialogsFragment);` to launcher intent.

**Comment by daimoniuma** [comment]
Lol, I got your idea. param.thisObject should be casted to Activity to setIntent. It is working perfectly now. Thank you! ❤
