### ISSUE TITLE
When i've hooked native jni method,xposed told me "NoSuchMethodError"

### ISSUE THREAD

**Issue by the7urn1ph34d** [rovo89/XposedBridge#177]
# SO where was i wrong?

## Method Declaration:

```
.method protected native Connect(Ljava/lang/String;Ljava/lang/String;ILio/rong/imlib/NativeObject$ConnectAckCallback;Z)V
.end method
```

## My Code :

```
final Class<?> ArgClass= XposedHelpers.findClass("io.rong.imlib.NativeObject$ConnectAckCallback", lpparam.classLoader);

            XposedHelpers.findAndHookMethod(
                    "io.rong.imlib.NativeObject",
                    lpparam.classLoader,
                    "Connect",
                    String.class,
                    String.class,
                    Integer.class,
                    ArgClass,
                    Boolean.class,
        new XC_MethodHook(){
                        @Override
                        protected void beforeHookedMethod(MethodHookParam param)
                                throws Throwable {
                       }
                        protected void afterHookedMethod(MethodHookParam param)
                                throws Throwable {
                        }
                    });
```

## ERROR LOG:

```
07-04 11:15:46.532 E/Xposed  ( 8103): java.lang.NoSuchMethodError: io.rong.imlib.NativeObject#Connect(java.lang.String,java.lang.String,java.lang.Integer,io.rong.imlib.NativeObject.ConnectAckCallback,java.lang.Boolean)#exact
07-04 11:15:46.532 E/Xposed  ( 8103): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:341)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:182)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:257)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at trojan.funchooker.hooker.handleLoadPackage(hooker.java:115)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:116)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at android.os.Looper.loop(Looper.java:135)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at java.lang.reflect.Method.invoke(Native Method)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at java.lang.reflect.Method.invoke(Method.java:372)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
07-04 11:15:46.532 E/Xposed  ( 8103): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```
# Thanks for your help~

**Comment by rovo89** [comment]
`Integer` and `int` are different types. The method definition is using the latter, so you have to use `int.class`. Same for `boolean.class`. Also, you don't need the `ArgClass` variable - just use the class name instead of a class reference in your `findAndHookMethod()`.

All of this is explained here:
http://api.xposed.info/reference/de/robv/android/xposed/XposedHelpers.html#findAndHookMethod(java.lang.String,%20java.lang.ClassLoader,%20java.lang.String,%20java.lang.Object...)

**Comment by the7urn1ph34d** [comment]
wow!! it works , thanks for your rapid reply.   : )

**Comment by Marin111** [comment]
HI
i meet a question 
Can xp hook this Method (below Function) it is just An register Function.
AND there is A Context param How to hook
private static native String nativesger (Context context, long j, String str, byte[] bArr)

**Comment by Marin111** [comment]
HI
i meet a question 
Can xp hook this Method (below Function) it is just An register Function.
AND there is A Context param How to hook
`private static native String nativesger (Context context, long j, String str, byte[] bArr) `
