### ISSUE TITLE
XC_MethodHook 's callback is not be called

### ISSUE THREAD

**Issue by NateZh** [rovo89/XposedBridge#182]
it's a public method .
![image](https://user-images.githubusercontent.com/7836381/28953598-c54d1470-790b-11e7-9375-e06c77f64de8.png)

i try to print log but not work
![image](https://user-images.githubusercontent.com/7836381/28953653-34d2864a-790c-11e7-85cc-339df10cc168.png)

only show packageName as below
![image](https://user-images.githubusercontent.com/7836381/28953670-51a0f8f6-790c-11e7-9625-8b5d827bb7ac.png)

![image](https://user-images.githubusercontent.com/7836381/28953692-7c1a8110-790c-11e7-9431-2f15b77a95bb.png)

log as below:
08-04 11:30:49.781 I/Xposed  ( 2266): -----------------
08-04 11:30:49.781 I/Xposed  ( 2266): Starting Xposed version 87, compiled for SDK 22
08-04 11:30:49.781 I/Xposed  ( 2266): Device: m1 note (Meizu), Android version 5.1 (SDK 22)
08-04 11:30:49.781 I/Xposed  ( 2266): ROM: Flyme 6.1.0.0A
08-04 11:30:49.781 I/Xposed  ( 2266): Build fingerprint: Meizu/m1note/m1note:5.1/LMY47D/1495881950:user/release-keys
08-04 11:30:49.781 I/Xposed  ( 2266): Platform: arm64-v8a, 64-bit binary, system server: yes
08-04 11:30:49.781 I/Xposed  ( 2266): SELinux enabled: yes, enforcing: no
08-04 11:30:52.648 I/Xposed  ( 2266): -----------------
08-04 11:30:52.648 I/Xposed  ( 2266): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
08-04 11:30:52.988 I/Xposed  ( 2266): Detected ART runtime
08-04 11:30:52.990 I/Xposed  ( 2266): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
08-04 11:30:53.162 I/Xposed  ( 2266): Loading modules from /data/app/com.hj.xposedtest-1/base.apk
08-04 11:30:53.165 I/Xposed  ( 2266):   Loading class com.hj.xposedtest.XModule
08-04 11:30:56.652 I/Xposed  ( 2571): x XposedBridge pn:android
...
08-04 11:33:28.753 I/Xposed  ( 9025): x XposedBridge pn:com.hj.littleSecretary
08-04 11:33:29.260 I/Xposed  ( 9088): x XposedBridge pn:com.hj.littleSecretary

**Comment by NateZh** [comment]
some more err info  maybe the cause  ?

08-04 10:41:26.850 7537-7537/? D/StrictMode: StrictMode policy violation; ~duration=104 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
                                                 at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1171)
                                                 at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1058)
                                                 at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:612)
                                                 at android.database.sqlite.SQLiteConnection.setJournalSizeLimit(SQLiteConnection.java:286)
                                                 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:229)
                                                 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:206)
                                                 at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                 at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:836)
                                                 at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
                                                 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
                                                 at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1286)
                                                 at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
                                                 at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                 at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
                                                 at com.android.providers.contacts.ContactsDatabaseHelper.getAllAccountsWithDataSets(ContactsDatabaseHelper.java:5521)
                                                 at com.android.providers.contacts.aggregation.AccountsManager.<init>(AccountsManager.java:46)
                                                 at com.android.providers.contacts.ContactsProvider2.initialize(ContactsProvider2.java:1717)
                                                 at com.android.providers.contacts.ContactsProvider2.onCreate(ContactsProvider2.java:1662)
                                                 at android.content.ContentProvider.attachInfo(ContentProvider.java:1840)
                                                 at android.content.ContentProvider.attachInfo(ContentProvider.java:1815)
                                                 at android.app.ActivityThread.installProvider(ActivityThread.java:5554)
                                                 at android.app.ActivityThread.installContentProviders(ActivityThread.java:5127)
                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5052)
                                                 at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
                                                 at android.app.ActivityThread.handleBindApplication(<Xposed>)
                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:181)
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
                                                 at android.os.Handler.dispatchMessage(Handler.java:111)
                                                 at android.os.Looper.loop(Looper.java:194)
                                                 at android.app.ActivityThread.main(ActivityThread.java:5868)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
08-04 10:41:26.850 7537-7537/? D/StrictMode: StrictMode policy violation; ~duration=102 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
                                                 at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1171)
                                                 at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1058)
                                                 at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:612)
                                                 at android.database.sqlite.SQLiteConnection.setAutoCheckpointInterval(SQLiteConnection.java:274)
                                                 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:230)
                                                 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:206)
                                                 at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                 at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:836)
                                                 at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
                                                 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
                                                 at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1286)
                                                 at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
                                                 at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                 at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
                                                 at com.android.providers.contacts.ContactsDatabaseHelper.getAllAccountsWithDataSets(ContactsDatabaseHelper.java:5521)
                                                 at com.android.providers.contacts.aggregation.AccountsManager.<init>(AccountsManager.java:46)
                                                 at com.android.providers.contacts.ContactsProvider2.initialize(ContactsProvider2.java:1717)
                                                 at com.android.providers.contacts.ContactsProvider2.onCreate(ContactsProvider2.java:1662)
                                                 at android.content.ContentProvider.attachInfo(ContentProvider.java:1840)
                                                 at android.content.ContentProvider.attachInfo(ContentProvider.java:1815)
                                                 at android.app.ActivityThread.installProvider(ActivityThread.java:5554)
                                                 at android.app.ActivityThread.installContentProviders(ActivityThread.java:5127)
                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5052)
                                                 at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                 at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
                                                 at android.app.ActivityThread.handleBindApplication(<Xposed>)
                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:181)
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
                                                 at android.os.Handler.dispatchMessage(Handler.java:111)
                                                 at android.os.Looper.loop(Looper.java:194)
                                                 at android.app.ActivityThread.main(ActivityThread.java:5868)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
                                                 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by Massi-X** [comment]
First, maybe you can use some more words?
Second you are showing that all is working... Where is the problem? Your hook log the PKG name, and indeed you see the PKG name in the log. I really can't understand...

**Comment by Massi-X** [comment]
For the second comment I can't understand how this is related to your problem.
PS. Wrap logs in code tag

**Comment by rovo89** [comment]
No feedback => closed.
