### ISSUE TITLE
Parameter type must either be specified as Class or String

### ISSUE THREAD

**Issue by daimoniuma** [rovo89/XposedBridge#189]
Got issue. 🌚 
```
ClassNotFoundError: parameter type must either be specified as Class or String
09-30 21:45:09.834 E/Xposed  ( 9541): 	at de.robv.android.xposed.XposedHelpers.getParameterClasses(XposedHelpers.java:509)
09-30 21:45:09.834 E/Xposed  ( 9541): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:182)
```
Code:
```
Class<?> newsEntry = XposedHelpers.findClassIfExists(class_NewsEntry, lpparam.classLoader);
			
			if(newsEntry == null)
				return;
				
			String className = class_Posts;
			String methodName = method_Posts_buildItems;
			Object[] objects = new Object[] {newsEntry, boolean.class, String.class, boolean.class, boolean.class, View.OnClickListener.class, boolean.class, String.class, int.class};
			
			if(!checkMethod(lpparam, className, methodName, objects))
				return;
			
			XposedHelpers.findAndHookMethod(className, lpparam.classLoader, methodName, objects, new XC_MethodHook() {
```

**Comment by rovo89** [comment]
You can't use it that way. Yes, you could pass an array for the varargs parameter, but you're not doing that, you're actually passing two parameters: an Object array plus the callback (instead of 9 class parameters plus the callback). So either put the callback into the Object array or get rid of that array completely.

**Comment by daimoniuma** [comment]
Sorry about that. 🌚
