### ISSUE TITLE
MIUI 9 launcher keep crashing when I rotate screen

### ISSUE THREAD

**Issue by mcitew** [rovo89/XposedBridge#218]
I am posting this because the crash log there is a mention of xposed. 

Using xposed v88.2 sdk 24 on Mi Max Prime xiaomi.eu version 7.11.2.

Whenever I open a app and then rotate the screen, the launcher will crash.

Disable xposed there is no crash.

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
	at android.app.ResourcesManager.applyConfigurationToResourcesLocked(ResourcesManager.java)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by perfiction** [comment]
Did you try disabling Reource Hooks in Xposed Installer?

**Comment by mcitew** [comment]
Arh, I ticked the setting the problem is gone. Thanks for the pointer. Some modules won't work after that.

**Comment by mcitew** [comment]
Funny that the crash can disappear after running for some time and reoccur after a reboot.

**Comment by mcitew** [comment]
The crash does not happen after installing a newer ROM. So likely this is a case of the ROM itself has problem but catch as a crash in xposed.
