### ISSUE TITLE
MIUI 9 (7.12.1) Security app Xposed issue

### ISSUE THREAD

**Issue by endersgergo** [rovo89/XposedBridge#223]
The security app stops when open the application manager.
Crash log (xposed appears here):
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miui.securitycenter/com.miui.appmanager.AppManagerMainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6342)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
	at com.miui.appmanager.AppManagerMainActivity.aaN()
	at com.miui.appmanager.AppManagerMainActivity.initData()
	at com.miui.appmanager.AppManagerMainActivity.onCreate()
	at android.app.Activity.performCreate(Activity.java:6847)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
	... 10 more

**Comment by endersgergo** [comment]
Also, Xposed version is 88.2 (arm64 sdk24)

**Comment by endersgergo** [comment]
Not the Xposed caused the the issue, same problem without it
