### ISSUE TITLE
Xposed info failing to load for the package com.lge.sui.widget

### ISSUE THREAD

**Issue by barebackbandit** [rovo89/XposedBridge#227]
I have a brand new (<1 month old) LG K20 Plus. I am not experiencing longer than normal boot time (in reference to the other currently open issue with the LG V20). I am not experiencing any error messages, nor is there any issue that prompted me to look in the Xposed log; just messing around. Anyways, in the Xposed log, I see the a line about Xposed info failing to load for the com.lge.sui.widget package. This is repeated many many times. Is this any cause for alarm/concern? Full log below.

```
01-10 04:37:17.048 I/Xposed  (  538): -----------------
01-10 04:37:17.048 I/Xposed  (  538): Starting Xposed version 89, compiled for SDK 24
01-10 04:37:17.048 I/Xposed  (  538): Device: LG-TP260 (LGE), Android version 7.0 (SDK 24)
01-10 04:37:17.048 I/Xposed  (  538): ROM: NRD90U
01-10 04:37:17.048 I/Xposed  (  538): Build fingerprint: lge/lv517_tmo_us/lv517:7.0/NRD90U/1729119266dda:user/release-keys
01-10 04:37:17.049 I/Xposed  (  538): Platform: armeabi-v7a, 32-bit binary, system server: yes
01-10 04:37:17.049 I/Xposed  (  538): SELinux enabled: yes, enforcing: yes
01-10 04:37:18.097 I/Xposed  (  538): -----------------
01-10 04:37:18.097 I/Xposed  (  538): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
01-10 04:37:19.221 I/Xposed  (  538): Detected ART runtime
01-10 04:37:19.229 I/Xposed  (  538): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
01-10 04:37:19.635 I/Xposed  (  538): Loading modules from /data/app/com.intangibleobject.securesettings.plugin-1/base.apk
01-10 04:37:19.677 I/Xposed  (  538):   Loading class com.intangibleobject.securesettings.plugin.xposed.Main
01-10 04:37:19.701 E/Xposed  (  538): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.LockSettingsService
01-10 04:37:19.701 E/Xposed  (  538): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
01-10 04:37:19.701 E/Xposed  (  538): 	at com.intangibleobject.securesettings.plugin.xposed.a.a(LockSettings.java:35)
01-10 04:37:19.701 E/Xposed  (  538): 	at com.intangibleobject.securesettings.plugin.xposed.Main.initZygote(Main.java:31)
01-10 04:37:19.701 E/Xposed  (  538): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:552)
01-10 04:37:19.701 E/Xposed  (  538): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:466)
01-10 04:37:19.701 E/Xposed  (  538): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:96)
01-10 04:37:19.701 E/Xposed  (  538): Caused by: java.lang.ClassNotFoundException: com.android.server.LockSettingsService
01-10 04:37:19.701 E/Xposed  (  538): 	at java.lang.Class.classForName(Native Method)
01-10 04:37:19.701 E/Xposed  (  538): 	at java.lang.Class.forName(Class.java:400)
01-10 04:37:19.701 E/Xposed  (  538): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
01-10 04:37:19.701 E/Xposed  (  538): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
01-10 04:37:19.701 E/Xposed  (  538): 	... 5 more
01-10 04:37:19.701 E/Xposed  (  538): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.server.LockSettingsService" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]
01-10 04:37:19.701 E/Xposed  (  538): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-10 04:37:19.701 E/Xposed  (  538): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
01-10 04:37:19.701 E/Xposed  (  538): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-10 04:37:19.701 E/Xposed  (  538): 	... 9 more
01-10 04:37:19.701 I/Xposed  (  538): SecureSettings:Initialized
01-10 04:37:19.701 I/Xposed  (  538): Loading modules from /data/app/com.evbadroid.wicapdemo-1/base.apk
01-10 04:37:19.723 I/Xposed  (  538):   Loading class com.evbadroid.wicap.WiCapXposed
01-10 04:37:19.724 E/Xposed  (  538):     Failed to load class com.evbadroid.wicap.WiCapXposed
01-10 04:37:19.724 E/Xposed  (  538): java.lang.ClassNotFoundException: Didn't find class "com.evbadroid.wicap.WiCapXposed" on path: DexPathList[[zip file "/data/app/com.evbadroid.wicapdemo-1/base.apk"],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
01-10 04:37:19.724 E/Xposed  (  538): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-10 04:37:19.724 E/Xposed  (  538): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
01-10 04:37:19.724 E/Xposed  (  538): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-10 04:37:19.724 E/Xposed  (  538): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:536)
01-10 04:37:19.724 E/Xposed  (  538): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:466)
01-10 04:37:19.724 E/Xposed  (  538): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:96)
01-10 04:37:36.155 W/Xposed  ( 2058): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:37:50.986 W/Xposed  ( 3053): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:38:16.614 I/XposedInstaller( 4359): Downloaded http://dl.xposed.info/repo/partial/13704.xml.gz with status 0 (error: null), size 35211 bytes
01-10 04:38:17.257 I/XposedInstaller( 4359): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 13751 (20 new / 0 removed modules)
01-10 04:38:18.028 W/Xposed  ( 4457): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:38:19.181 W/Xposed  ( 4544): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:38:43.957 W/Xposed  ( 5590): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:38:44.421 W/Xposed  ( 5629): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:38:58.852 I/Xposed  ( 6374): Loading package com.intangibleobject.securesettings.plugin
01-10 04:39:00.677 W/Xposed  ( 6528): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:39:12.103 W/Xposed  ( 7178): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:39:19.909 W/Xposed  ( 7555): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:39:20.722 W/Xposed  ( 7615): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:39:20.922 W/Xposed  ( 7631): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:39:21.250 W/Xposed  ( 7649): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:39:32.614 W/Xposed  ( 8154): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:39:37.830 W/Xposed  ( 8459): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:39:46.430 W/Xposed  ( 8873): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:39:47.130 W/Xposed  ( 8927): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:45:32.771 W/Xposed  (10747): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:45:34.527 W/Xposed  (10874): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:45:35.433 W/Xposed  (10943): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:45:59.124 I/XposedInstaller( 4359): updating modules.list
01-10 04:47:31.528 W/Xposed  (11686): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:47:32.770 W/Xposed  (11805): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:47:32.951 W/Xposed  (11824): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:47:38.246 W/Xposed  (12096): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:47:40.416 W/Xposed  (12192): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:47:41.092 I/XposedInstaller( 4359): updating modules.list
01-10 04:47:41.682 I/Xposed  (12257): Loading package com.intangibleobject.securesettings.plugin
01-10 04:47:41.890 W/Xposed  (12277): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:49:03.723 W/Xposed  (12741): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:49:04.963 W/Xposed  (12872): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:49:05.132 W/Xposed  (12893): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:49:15.504 I/XposedInstaller( 4359): updating modules.list
01-10 04:49:16.543 I/Xposed  (13492): Loading package com.intangibleobject.securesettings.plugin
01-10 04:49:16.770 W/Xposed  (13513): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:57:05.374 W/Xposed  (14843): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:57:06.840 W/Xposed  (14974): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:57:07.276 W/Xposed  (15022): Failed to load Xposed info for /system/framework/com.lge.sui.widget/oat/arm/com.lge.sui.widget.odex: Unable to open '/data/dalvik-cache/arm/system@framework@com.lge.sui.widget@oat@arm@com.lge.sui.widget.odex@xposed' : No such file or directory
01-10 04:57:13.663 I/XposedInstaller( 4359): updating modules.list
```

**Comment by Artith1987** [comment]
Samsung G532G

**Comment by Artith1987** [comment]
Comment on issue

**Comment by Artith1987** [comment]
ON Issue Xposed Device Samsung G532G

**Comment by Artith1987** [comment]
You’re not receiving notifications from this thread.

**Comment by Artith1987** [comment]
Comnent on githup.com

**Comment by Artith1987** [comment]
Notifications for this thread

**Comment by Artith1987** [comment]
You’re receiving notifications because you commented.

**Comment by Artith1987** [comment]
Internet

**Comment by Artith1987** [comment]
Receiving access

**Comment by SWeeTS51088** [comment]
Was there any resolve to this, if it even needed one? I'm having a similar "issue" on my LG Aristo 2 (LM-X210MA).
