### ISSUE TITLE
Didn't find class "de.robv.android.xposed.XSharedPreferences"

### ISSUE THREAD

**Issue by magicbaby810** [rovo89/XposedBridge#249]
Caused by: java.lang.ClassNotFoundException: Didn't find class "de.robv.android.xposed.XSharedPreferences" on path: DexPathList[[zip file "/data/app/com.sk.frankenstein-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.sk.frankenstein.util.SharedPreferencesUtils.getInstance(SharedPreferencesUtils.java:23) 
        at com.sk.frankenstein.util.SharedPreferencesUtils.getBooleanValue(SharedPreferencesUtils.java:30) 
        at com.sk.frankenstein.ui.MainActivity.checkPermissions(MainActivity.java:166) 
        at com.sk.frankenstein.ui.MainActivity.initData(MainActivity.java:122) 
        at com.sk.frankenstein.base.BaseActivity.onCreate(BaseActivity.java:20) 
        at android.app.Activity.performCreate(Activity.java:6075) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2281) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1306) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5270) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:915) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:710) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
    	Suppressed: java.lang.ClassNotFoundException: Didn't find class "de.robv.android.xposed.XSharedPreferences" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex", dex file "/data/dalvik-cache/xposed_XTypedArraySuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 20 more
    		Suppressed: java.lang.ClassNotFoundException: de.robv.android.xposed.XSharedPreferences
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        			... 21 more

**Comment by magicbaby810** [comment]
why?  don't find class de.robv.android.xposed.XSharedPreferences?? I load this XposedBridgeApi-54.jar

**Comment by kwaiching** [comment]
Anyone solved it?
