### ISSUE TITLE
Crash Report In HuaWei Nova 2s Honor 9i

### ISSUE THREAD

**Issue by JinWoKe** [rovo89/XposedBridge#261]
java.lang.IllegalStateException: Service user.xposed.app does not exist
08-01 11:12:56.474 E/Xposed  ( 1126): 	at de.robv.android.xposed.services.BinderService.<init>(BinderService.java:163)
08-01 11:12:56.474 E/Xposed  ( 1126): 	at de.robv.android.xposed.services.BinderService.getService(BinderService.java:27)
08-01 11:12:56.474 E/Xposed  ( 1126): 	at de.robv.android.xposed.SELinuxHelper.initForProcess(SELinuxHelper.java:73)
08-01 11:12:56.474 E/Xposed  ( 1126): 	at de.robv.android.xposed.XposedInit$4$1.beforeHookedMethod(XposedInit.java:174)
08-01 11:12:56.474 E/Xposed  ( 1126): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
08-01 11:12:56.474 E/Xposed  ( 1126): 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
08-01 11:12:56.474 E/Xposed  ( 1126): 	at com.android.server.SystemServer.run(SystemServer.java:516)
08-01 11:12:56.474 E/Xposed  ( 1126): 	at com.android.server.SystemServer.main(SystemServer.java:375)
08-01 11:12:56.474 E/Xposed  ( 1126): 	at java.lang.reflect.Method.invoke(Native Method)
08-01 11:12:56.474 E/Xposed  ( 1126): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
08-01 11:12:56.474 E/Xposed  ( 1126): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
08-01 11:12:56.474 E/Xposed  ( 1126): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by JinWoKe** [comment]
Please ! SomeOne Who Can Help Me ?????
