### ISSUE TITLE
XSharedPreferences crashed on LP

### ISSUE THREAD

**Issue by pylerSM** [rovo89/XposedBridge#36]
04-04 05:13:34.919 F/StrictMode(32013): Stack is too large: numViolations=5 policy=#387 front=  at de.robv.android.xposed.services.DirectAccessService.statFile(DirectAccessService.java:33)
04-04 05:13:34.919 F/StrictMode(32013):     at de.robv.android.xposed.XSharedPreferences.hasFileChanged(XSharedPreferences.java:173)

Full log is here: http://forum.xda-developers.com/showpost.php?p=59888087&postcount=681

**Comment by rovo89** [comment]
These error messages are about strict mode, which should log/prevent access things like file access in the main thread. Not sure if I get this correctly, but it seems that the file access triggered by your call to `reload()` isn't allowed by a policy set by one of the callers.

Assuming this issue can be reproduced, please check if not reloading the settings solves it. As mentioned before, this can be an expensive call anyway, especially once the SELinux policy starts using separate contexts levels per app and the `DirectAccessService` can no longer be used.

If this does help, then please put a simple file access there yourself and see if it violates the strict mode.

**Comment by pylerSM** [comment]
Try catch will not help? Since it is not very important to refresh if every half of second or so.

**Comment by rovo89** [comment]
The actual crash is not the strict mode violation, it's the OutOfMemoryError. I don't think you can properly catch that. The more interesting question would be why it tries to allocate so much memory. Maybe there are lots and lots of violations?

Anyway, did you try what I said?

**Comment by pylerSM** [comment]
Yes, without reloading there are no crashes.

**Comment by rovo89** [comment]
Can you try to wrap your reload() command like this?

``` java
StrictMode.ThreadPolicy oldPolicy = StrictMode.allowThreadDiskReads();
try {
    pref.reload();
} finally {
    StrictMode.setThreadPolicy(oldPolicy);
}
```

This might allow your module to read from the disk in the place where you do so.

**Comment by pylerSM** [comment]
Thanks for advice, I will try & report.

**Comment by pylerSM** [comment]
Tried with code (https://github.com/pylerSM/XInstaller/blob/master/src/com/pyler/xinstaller/XInstaller.java#L1286) and device can't boot.

**Comment by pylerSM** [comment]
so what exactly causes fast reboot? So we can atleast prevent somehow.

**Comment by rovo89** [comment]
> and device can't boot.

So you're saying it works fine without restoring the original policy? Maybe it would work better if you indeed restored the original policy (`oldPolicy` instead of `oldPolicy2`). Is it even necessary to enable writes as well? And why are you catching all Exceptions? Which ones do you expect there? You should at least log them, otherwise you might miss some importing debugging information.

Anyway, please keep us updated when you find out more (e.g. why it doesn't boot, or even how to fix it).

> so what exactly causes fast reboot? So we can atleast prevent somehow.

Usually, a fast reboot happens when either the Zygote or (more likely) system_server process quits, either explicitely or due to an uncaught exception/error or because of a native crash. But catching such situations is the wrong approach, I don't like to just "fix" symptoms unless I definitely know the root cause and know that a proper fix is impossible (or not worth the effort).

**Comment by pylerSM** [comment]
I can try but I think i tried restore even oldPolicy some days ago and result was same, device failee to boot. I will verify it again.

Catching exception was my naive idea to fix problems during re-loading. Yes,it is useless there.

**Comment by pylerSM** [comment]
Tested with "oldPolicy" (DiskReads), device can't boot.

**Comment by rovo89** [comment]
OK, then please let us know once you find out more details.

**Comment by pylerSM** [comment]
I will do, but I have no idea how to fix it properly. Maybe some kind of timer to allow/deny getting preference value after X (mili)second or what.

Maybe you can help me with this different issue (http://forum.xda-developers.com/xposed/class-using-boot-class-loader-stack-t3030446/page2)?

**Comment by tonyp** [comment]
I recently played around a bit with the StrictMode as well while trying to debug an issue. I believe you can't change the policy during `initZygote` as this is executed too early during boot. It worked fine for me in `handleLoadPackage`, so you might want to consider moving your hooks there.

Oh and my log did show me a descriptive error when I tried to access the StrictMode policy during initZygote which you probably just swallowed with your catch-block.

**Comment by pylerSM** [comment]
Hmm my code "changes" Strict Policy mode when reloading prefs. So I should do it just once? Can you show example code?

Yes, I could move zygote hooks into loadPackage.

**Comment by tonyp** [comment]
No I didn't say that. I just meant that you shouldn't try to change the policy (which probably isn't even yet set) during boot. There's no need to reload the preferences here anyways. So moving all calls to your reloadPreferences method from initZygote to loadPackage might already fix the issue.

But your code here seems a bit flawed. The code @rovo89 posted is correct, I think in your finally-block you should set the policy to oldPolicy (and get rid of the whole oldPolicy2 line).

**Comment by pylerSM** [comment]
Ok, I will move hooks in which I call reloadPreferences() and report results.

**Comment by pylerSM** [comment]
Looks like it didn't help. I moved hooks from initZygote to handleLoadPackage.
And reloadPreferences code is: https://github.com/pylerSM/XInstaller/blob/master/src/com/pyler/xinstaller/XInstaller.java#L1297

Maybe you can help if it is a very specific bug... Download latest beta of my module: http://dl-xda.xposed.info/modules/com.pyler.xinstaller_v466_a691a1.apk
Activate it, reboot device. Then go to module settings and change many settings. You should see forced reboot.

**Comment by tonyp** [comment]
Installed the linked version, activated it, rebooted and immediately run into a bootloop with an `android.os.TransactionTooLargeException`.
Log: http://pastebin.com/fYVUGQHm

I had a quick glance at your code and saw that you are calling reload() quite often. Is a reload really needed within all hooks or are some executed after another and you could cut down here a bit? Although the error in my log doesn't appear to be related to the StrictMode issue at all.

And I have a general question (which probably is for @rovo89 to answer): Is it advisable to create references to the hooks in `initZygote` as it is done here? I haven't seen this approach before. Or might this be related to the error?

P.S.: Your StrictMode code still doesn't look quite right. Why do you check the `changePolicy` boolean in the `finally` block? The `StrictMode.setThreadPolicy(oldPolicy)` changes the policy _back_ to the original one before you changed it to `allowThreadDiskReads`.
As far as I understand it: The `StrictMode.ThreadPolicy oldPolicy = StrictMode.allowThreadDiskReads();` line changes your StrictMode policy and stores a reference to the old one, then you execute your code within the changed policy, then you reset it to the old one in the finally-block.

**Comment by rovo89** [comment]
Is the settings file that big? Or is there much going on? From http://developer.android.com/reference/android/os/TransactionTooLargeException.html:

> The Binder transaction buffer has a limited fixed size, currently 1Mb, which is shared by all transactions in progress for the process. Consequently this exception can be thrown when there are many transactions in progress even when most of the individual transactions are of moderate size.

.

> Is it advisable to create references to the hooks in initZygote as it is done here?

I wouldn't put this in a best-practices guide (especially not the `hookAllMethods()` part of it), but it should be working.

**Comment by pylerSM** [comment]
Restoring policy causes problem with not booting so there is boolean to test it.

**Comment by pylerSM** [comment]
Prefs file has 2,86 KB

**Comment by C3C0** [comment]
@tonyp 
Just to bring some details to your attention. Even if you call reload() often it internally checks whether file has been changed before starting load-from-disk operation. https://github.com/rovo89/XposedBridge/blob/master/src/de/robv/android/xposed/XSharedPreferences.java#L121
This should avoid frequent load happening, although I'm not sure how expensive hasFileChanged() operation is. Anyway, this is not to justify frequent reload() call. I think there's always a way to prevent it. One of my approaches is to register broadcast receiver within hooked process that listens for changes done by user in module settings UI; which reload prefs only when pref change occurs.

**Comment by rovo89** [comment]
> although I'm not sure how expensive hasFileChanged() operation is

It still has to `stat()` the file (via the binder service). Not sure what's more expensive - this additional binder call or the creation of a new thread. I have built the `readFile()` call with some logic that doesn't read the file again if modification time and size are the same as given in the arguments. So it has the file changed check built in on native side.

It would be good to see which transactions are running, not sure if there's a way to do it.
Also, there might be a leak of parcels here: https://github.com/rovo89/XposedBridge/blob/art/src/de/robv/android/xposed/services/BinderService.java#L77

**Comment by pylerSM** [comment]
On pre-Lollipop I have no problems.

**Comment by C3C0** [comment]
@pylerSM 
The first I would personally do would be to move all those hook definitions from zygote inside if's for packages they belong to within handleLoadPackage, . It doesn't make too much sense to me to have them within zygote and maybe it can have undesired side effects.

**Comment by rovo89** [comment]
Could we please stay on topic? On pre-Lollipop, the files were access directly, no binders or anything involved.
Style advice is nice, but keep in mind how many people are watching this repository.

**Comment by pylerSM** [comment]
How many of them are non-developers? This is place by developers for developers, so activity is normal here and I am thankful to anyone who tries to help me and others :)

Okey,
- I moved hooks to specific packages, sadly no progress, still reboot after changing some preferences
- Tried all combinations of setting policy and restoring it.. no progress.

I got some logs and I checked them for "android.os.TransactionTooLargeException". I had none.

These two cause problems:

E/AndroidRuntime(30999): **\* FATAL EXCEPTION IN SYSTEM PROCESS: XSharedPreferences-load

E/AndroidRuntime(30999): java.lang.IllegalArgumentException: Offset 0 / Length 0 is out of range for /data/data/com.pyler.xinstaller/shared_prefs/com.pyler.xinstaller_preferences.xml with size 3141

E/AndroidRuntime(30999):    at de.robv.android.xposed.services.BinderService.readFile(BinderService.java:130)

E/AndroidRuntime(30999):    at de.robv.android.xposed.services.BinderService.readFile(BinderService.java:93)

E/AndroidRuntime(30999):    at de.robv.android.xposed.services.BaseService.getFileInputStream(BaseService.java:131)

E/AndroidRuntime(30999):    at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:120)

E/AndroidRuntime(30999):    at de.robv.android.xposed.XSharedPreferences.access$0(XSharedPreferences.java:112)

E/AndroidRuntime(30999):    at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:105)```

and

W/XSharedPreferences( 8250): getSharedPreferences

W/XSharedPreferences( 8250): java.io.IOException: Error 13 while reading /data/data/com.pyler.xinstaller/shared_prefs/com.pyler.xinstaller_preferences.xml

W/XSharedPreferences( 8250):    at de.robv.android.xposed.services.BaseService.throwCommonIOException(BaseService.java:158)

W/XSharedPreferences( 8250):    at de.robv.android.xposed.services.BinderService.readFile(BinderService.java:133)

W/XSharedPreferences( 8250):    at de.robv.android.xposed.services.BinderService.readFile(BinderService.java:93)

W/XSharedPreferences( 8250):    at de.robv.android.xposed.services.BaseService.getFileInputStream(BaseService.java:131)

W/XSharedPreferences( 8250):    at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:120)

W/XSharedPreferences( 8250):    at de.robv.android.xposed.XSharedPreferences.access$0(XSharedPreferences.java:112)

W/XSharedPreferences( 8250):    at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:105)

**Comment by pylerSM** [comment]
So error 13 means EACCES (Permission denied?)

**Comment by rovo89** [comment]
> How many of them are non-developers? This is place by developers for developers, so activity is normal here and I am thankful to anyone who tries to help me and others :)

Sure, it's good to see that people are giving advice. But still:
- 137 people are getting emails for every comment
- This particular issue is about crashes under certain circumstances when using XSharedPreferences on Lollipop, so unrelated topics should be kept to a minimum.

Yes, 13 means permission denied. That has to be expected when the file is updated frequently, as there's a short period of time where the file doesn't have the right permissions yet. For that reason, it's only a warning. The other error is most likely caused by an old version of Xposed that you (or your users) seem to be using. It should be a warning since XposedBridge v62 due to this: https://github.com/rovo89/XposedBridge/commit/b6f3732f681dea3fc20a487ed2b142ced5f7e1d1#diff-4397ef3de354831b145d73904927e511L130

**Comment by pylerSM** [comment]
The latest XB version fixed it, I have no forced reboots. So the issue was solved.

**Comment by pylerSM** [comment]
Btw, get we check for XposedBridge version from code (api?)

**Comment by C3C0** [comment]
XposedBridge.XPOSED_BRIDGE_VERSION

**Comment by pylerSM** [comment]
Ok, so I can inform users that they need XB > 62 for fixing this bug.

**Comment by rovo89** [comment]
So to sum up:
- The reload() call should be enclosed with code that sets and resets the StrictMode.
- XposedBridge v62 or higher is required to avoid issues caused by intermediate states (e.g. file is not written completely yet, file has wrong permissions).

Open questions:
- What about the issues mentioned by @tonyp? Why is the transaction buffer exhausted?
- Should XposedBridge take care about the StrictMode itself (in this and possibly other places)?
- Would it be less expensive/cleaner to always trigger startLoadFromDisk() when reload() is called (and a binder service would have to be used)?
  This would avoid the need for manipulating the StrictMode and one additional binder call in case the file was actually changed. The call that should read the file would otherwise detect that timestamp and size of the file hasn't changed, and everything else should already be adapted to handle this situation.
  The only disadvantage I see is that a new thread would be created more frequently.

**Comment by pylerSM** [comment]
1, Yes, this can be done even XSharedPreferences API level
2, Yea, right. 
3, I am not sure, but I have no such error in logs.
4, I think yes
5, If it helps and improves performance then why not.
