### ISSUE TITLE
java.lang.ClassCastException Resource with Gionee phones (Elife S5.1/Blu Vivo Air)

### ISSUE THREAD

**Issue by matthewn4444** [rovo89/XposedBridge#46]
I am unable to use any resource related apps currently on my vivo air because of the class collisions.

Here is the stacktrace:

```
Loading Xposed v54 (for Zygote)
Running ROM 'BLU_D980I_V11_GENERIC' with fingerprint <...>
Errors during Xposed initialization
java.lang.ClassCastException: class android.content.res.XResources doesn't extend class amigo.theme.core.res.GioneeResources
    at de.robv.android.xposed.XposedBridge.cloneToSubclass(XposedBridge.java:787)
    at de.robv.android.xposed.XposedBridge.hookResources(XposedBridge.java:365)
    at de.robv.android.xposed.XposedBridge.initXbridgeZygote(XposedBridge.java:267)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
    at dalvik.system.NativeStart.main(Native method)
```

The workaround for now is to use disabled resource hooks but I cannot use apps like GravityBox.

**Comment by rovo89** [comment]
This is a well-known issue:
http://forum.xda-developers.com/showpost.php?p=52801382&postcount=8
Currently, no fix is in sight.
