### ISSUE TITLE
NoSuchMethodError getDataNetworkTypeIconGemini on P6000 Lolipop

### ISSUE THREAD

**Issue by Gilfar** [rovo89/XposedBridge#55]
```
07-31 16:50:38.238 E/Xposed  ( 1043): java.lang.NoSuchMethodError: com.mediatek.systemui.ext.DefaultStatusBarPlugin#getDataNetworkTypeIconGemini(com.mediatek.systemui.ext.NetworkType,int)#exact
07-31 16:50:38.238 E/Xposed  ( 1043):   at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:170)
07-31 16:50:38.238 E/Xposed  ( 1043):   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:131)
07-31 16:50:38.238 E/Xposed  ( 1043):   at com.ceco.lollipop.gravitybox.ModStatusBar$28.afterHookedMethod(ModStatusBar.java:1141)
07-31 16:50:38.238 E/Xposed  ( 1043):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:664)
07-31 16:50:38.238 E/Xposed  ( 1043):   at com.mediatek.systemui.ext.PluginFactory.getStatusBarPlugin(<Xposed>)
07-31 16:50:38.238 E/Xposed  ( 1043):   at com.android.systemui.statusbar.SignalClusterView.apply(SignalClusterView.java:403)
07-31 16:50:38.238 E/Xposed  ( 1043):   at com.android.systemui.statusbar.policy.NetworkControllerImpl.refreshViews(NetworkControllerImpl.java:2043)
07-31 16:50:38.238 E/Xposed  ( 1043):   at com.android.systemui.statusbar.policy.NetworkControllerImpl.refreshViews(NetworkControllerImpl.java:1736)
07-31 16:50:38.238 E/Xposed  ( 1043):   at com.android.systemui.statusbar.policy.NetworkControllerImpl.onReceive(NetworkControllerImpl.java:662)
07-31 16:50:38.238 E/Xposed  ( 1043):   at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:912)
07-31 16:50:38.238 E/Xposed  ( 1043):   at android.os.Handler.handleCallback(Handler.java:815)
07-31 16:50:38.238 E/Xposed  ( 1043):   at android.os.Handler.dispatchMessage(Handler.java:104)
07-31 16:50:38.238 E/Xposed  ( 1043):   at android.os.Looper.loop(Looper.java:194)
07-31 16:50:38.238 E/Xposed  ( 1043):   at android.app.ActivityThread.main(ActivityThread.java:5534)
07-31 16:50:38.238 E/Xposed  ( 1043):   at java.lang.reflect.Method.invoke(Native Method)
07-31 16:50:38.238 E/Xposed  ( 1043):   at java.lang.reflect.Method.invoke(Method.java:372)
07-31 16:50:38.238 E/Xposed  ( 1043):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
07-31 16:50:38.238 E/Xposed  ( 1043):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
07-31 16:50:38.238 E/Xposed  ( 1043):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by rovo89** [comment]
That's from Gravity Box, not the framework. Please check if the module is supposed to be compatible with your ROM, and if yes, report it to the module's support thread.
