### ISSUE TITLE
Creating xposed module result to java.lang.NullPointerException: src == null Error

### ISSUE THREAD

**Issue by wejdan** [rovo89/XposedBridge#94]
I have decided to learn to write modules for xposed framework. I have written this code 

```

package de.robv.android.xposed.mods.mainPK;

import de.robv.android.xposed.IXposedHookLoadPackage;
import de.robv.android.xposed.XposedBridge;
import de.robv.android.xposed.callbacks.XC_LoadPackage.LoadPackageParam;

public class main implements IXposedHookLoadPackage {
    public void handleLoadPackage(final LoadPackageParam lpparam) throws Throwable {
        XposedBridge.log("TestMod: " + lpparam.packageName);
    }
}
```

However the code dose not work and when I look into the logcat I see this error 

```
E/Xposed  (  606): java.lang.NullPointerException: src == null
E/Xposed  (  606):  at java.lang.System.arraycopy(System.java:192)
E/Xposed  (  606):  at java.lang.String._getChars(String.java:825)
E/Xposed  (  606):  at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:148)
E/Xposed  (  606):  at java.lang.StringBuilder.append(StringBuilder.java:216)
E/Xposed  (  606):  at de.robv.android.xposed.mods.mainPK.main.handleLoadPackage(main.java:9)
E/Xposed  (  606):  at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
E/Xposed  (  606):  at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
E/Xposed  (  606):  at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
E/Xposed  (  606):  at de.robv.android.xposed.XposedBridge$4.afterHookedMethod(XposedBridge.java:285)
E/Xposed  (  606):  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:752)
E/Xposed  (  606):  at android.app.LoadedApk.<init>(<Xposed>)
E/Xposed  (  606):  at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1795)
E/Xposed  (  606):  at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1757)
E/Xposed  (  606):  at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1729)
E/Xposed  (  606):  at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2204)
E/Xposed  (  606):  at android.app.ContextImpl.createPackageContext(ContextImpl.java:2185)
E/Xposed  (  606):  at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:677)
E/Xposed  (  606):  at android.app.ActivityThread.installProvider(ActivityThread.java:5012)
E/Xposed  (  606):  at android.app.ActivityThread.installContentProviders(ActivityThread.java:4634)
E/Xposed  (  606):  at android.app.ActivityThread.installSystemProviders(ActivityThread.java:5220)
E/Xposed  (  606):  at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:10016)
E/Xposed  (  606):  at com.android.server.SystemServer.startOtherServices(SystemServer.java:492)
E/Xposed  (  606):  at com.android.server.SystemServer.run(SystemServer.java:285)
E/Xposed  (  606):  at com.android.server.SystemServer.main(SystemServer.java:186)
E/Xposed  (  606):  at java.lang.reflect.Method.invoke(Native Method)
E/Xposed  (  606):  at java.lang.reflect.Method.invoke(Method.java:372)
E/Xposed  (  606):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/Xposed  (  606):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/Xposed  (  606):  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:134)
```

I use cyanogenmod 12.1

**Comment by rovo89** [comment]
According to the crash log, you call `StringBuilder.append()`, but I don't see that in your code. Are you sure you compiled and test exactly the code you posted above?

**Comment by wejdan** [comment]
yes I am sure

**Comment by rovo89** [comment]
OK, then please upload the APK and I'll have a look.

**Comment by wejdan** [comment]
[TestMod.zip](https://github.com/rovo89/XposedBridge/files/234741/TestMod.zip)

**Comment by rovo89** [comment]
It seems that the problem is that you have compiled the Xposed API into your APK instead of just referencing it. I don't know that this would have such effects, but it's definitely the wrong way. Please follow these instructions closely to avoid that: https://github.com/rovo89/XposedBridge/wiki/Using-the-Xposed-Framework-API

Apart from that, please don't place your classes in de.robv.... but use your own namespace.

**Comment by DVDAndroid** [comment]
@wejdan Try to set Gradle version to 1.3.0

**Comment by rovo89** [comment]
Well, I had actually decompiled the APK, removed the Xposed API classes and compiled it again. Then it started to work... Unless apktool/smali/baksmali produce "better" dex files, I still think that this is the issue.

**Comment by rovo89** [comment]
The issue here seems to have been that the Xposed API has been compiled into the APK. Since Xposed v84, there's a warning about this, and future versions of Xposed will prevent such a module from being loaded at all.
