### ISSUE TITLE
Bug that may be caused by Xposed

### ISSUE THREAD

**Issue by vi** [rovo89/XposedBridge#96]
Is it a proper place to report Xposed bugs?

Sample of compatibility library can't be run: https://github.com/shkschneider/android_PreferenceFragmentCompat/issues/1

Backtrace is like this:

```
04-27 16:27:54.040 E/AndroidRuntime(26873): FATAL EXCEPTION: main
04-27 16:27:54.040 E/AndroidRuntime(26873): Process: android.support.v4.preference.demo, PID: 26873
04-27 16:27:54.040 E/AndroidRuntime(26873): java.lang.RuntimeException: Unable to start activity ComponentInfo{android.support.v4.preference.demo/android.support.v4.preference.demo.MainActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class Toolbar
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2294)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2344)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.app.ActivityThread.access$1100(ActivityThread.java:139)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.os.Looper.loop(Looper.java:136)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.app.ActivityThread.main(ActivityThread.java:5294)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at java.lang.reflect.Method.invokeNative(Native Method)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at java.lang.reflect.Method.invoke(Method.java:515)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at dalvik.system.NativeStart.main(Native Method)
04-27 16:27:54.040 E/AndroidRuntime(26873): Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class Toolbar
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:306)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.app.Activity.setContentView(Activity.java:1973)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.support.v4.preference.demo.MainActivity.onCreate(MainActivity.java:15)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.app.Activity.performCreate(Activity.java:5350)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258)
04-27 16:27:54.040 E/AndroidRuntime(26873):     ... 12 more
04-27 16:27:54.040 E/AndroidRuntime(26873): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.Toolbar" on path: DexPathList[[zip file "/data/app/android.support.v4.preference.demo-2.apk"],nativeLibraryDirectories=[/data/app-lib/android.support.v4.preference.demo-2, /vendor/lib, /system/lib, /data/datalib]]
04-27 16:27:54.040 E/AndroidRuntime(26873):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.view.LayoutInflater.createView(LayoutInflater.java:559)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:652)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:66)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
04-27 16:27:54.040 E/AndroidRuntime(26873):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
04-27 16:27:54.040 E/AndroidRuntime(26873):     ... 22 more
04-27 16:27:54.040 W/ActivityManager( 3204):   Force finishing activity android.support.v4.preference.demo/.MainActivity
```

Based on line `de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)` the application author things it may be bug in Xposed.

Pre-built APK is attached [here](https://github.com/shkschneider/android_PreferenceFragmentCompat/issues/1#issuecomment-215173038).

I haven't tried disabling Xposed or its modules yet.

**Comment by rovo89** [comment]
> Based on line de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) the application author things it may be bug in Xposed.

As you can see, that line comes immediately after `dalvik.system.NativeStart.main`. It's present in every stack trace when Xposed is installed because it's called when the system is being initialized, and therefore it doesn't give us any hint whether a crash is caused by Xposed or not.

> I haven't tried disabling Xposed or its modules yet.

That would have been helpful to prove that it's most likely not caused by Xposed.

The error is:

`android.view.InflateException: Binary XML file line #7: Error inflating class Toolbar`
and
`Didn't find class "android.view.Toolbar"`

So someone (either you or the lib author) referenced the class `android.view.Toolbar` in one of the view XMLs, but that doesn't exist. There is a class [`android.widget.Toolbar`](http://developer.android.com/reference/android/widget/Toolbar.html) though.

**Comment by vi** [comment]
Reproduced the bug with Xposed disabled (by pressing Power button at boot).

**Comment by rovo89** [comment]
OK, thanks for confirming that it's not caused by Xposed. As I said, it's probably just a typo in your view XML.
